/* Debug.c generated by valac 0.26.1.9-22126, the Vala compiler
 * generated from Debug.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO (photo_stream_utils_media_info_get_type ())
#define PHOTO_STREAM_UTILS_MEDIA_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO, PhotoStreamUtilsMediaInfo))
#define PHOTO_STREAM_UTILS_MEDIA_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO, PhotoStreamUtilsMediaInfoClass))
#define PHOTO_STREAM_UTILS_IS_MEDIA_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO))
#define PHOTO_STREAM_UTILS_IS_MEDIA_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO))
#define PHOTO_STREAM_UTILS_MEDIA_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO, PhotoStreamUtilsMediaInfoClass))

typedef struct _PhotoStreamUtilsMediaInfo PhotoStreamUtilsMediaInfo;
typedef struct _PhotoStreamUtilsMediaInfoClass PhotoStreamUtilsMediaInfoClass;
#define _photo_stream_utils_media_info_unref0(var) ((var == NULL) ? NULL : (var = (photo_stream_utils_media_info_unref (var), NULL)))
typedef struct _PhotoStreamUtilsMediaInfoPrivate PhotoStreamUtilsMediaInfoPrivate;

#define PHOTO_STREAM_UTILS_TYPE_COMMENT (photo_stream_utils_comment_get_type ())
#define PHOTO_STREAM_UTILS_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_COMMENT, PhotoStreamUtilsComment))
#define PHOTO_STREAM_UTILS_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_COMMENT, PhotoStreamUtilsCommentClass))
#define PHOTO_STREAM_UTILS_IS_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_COMMENT))
#define PHOTO_STREAM_UTILS_IS_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_COMMENT))
#define PHOTO_STREAM_UTILS_COMMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_COMMENT, PhotoStreamUtilsCommentClass))

typedef struct _PhotoStreamUtilsComment PhotoStreamUtilsComment;
typedef struct _PhotoStreamUtilsCommentClass PhotoStreamUtilsCommentClass;

#define PHOTO_STREAM_UTILS_TYPE_LOCATION (photo_stream_utils_location_get_type ())
#define PHOTO_STREAM_UTILS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_LOCATION, PhotoStreamUtilsLocation))
#define PHOTO_STREAM_UTILS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_LOCATION, PhotoStreamUtilsLocationClass))
#define PHOTO_STREAM_UTILS_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_LOCATION))
#define PHOTO_STREAM_UTILS_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_LOCATION))
#define PHOTO_STREAM_UTILS_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_LOCATION, PhotoStreamUtilsLocationClass))

typedef struct _PhotoStreamUtilsLocation PhotoStreamUtilsLocation;
typedef struct _PhotoStreamUtilsLocationClass PhotoStreamUtilsLocationClass;

#define PHOTO_STREAM_UTILS_TYPE_USER (photo_stream_utils_user_get_type ())
#define PHOTO_STREAM_UTILS_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_USER, PhotoStreamUtilsUser))
#define PHOTO_STREAM_UTILS_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_USER, PhotoStreamUtilsUserClass))
#define PHOTO_STREAM_UTILS_IS_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_USER))
#define PHOTO_STREAM_UTILS_IS_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_USER))
#define PHOTO_STREAM_UTILS_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_USER, PhotoStreamUtilsUserClass))

typedef struct _PhotoStreamUtilsUser PhotoStreamUtilsUser;
typedef struct _PhotoStreamUtilsUserClass PhotoStreamUtilsUserClass;

#define PHOTO_STREAM_UTILS_TYPE_MEDIA (photo_stream_utils_media_get_type ())
#define PHOTO_STREAM_UTILS_MEDIA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA, PhotoStreamUtilsMedia))
#define PHOTO_STREAM_UTILS_MEDIA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_MEDIA, PhotoStreamUtilsMediaClass))
#define PHOTO_STREAM_UTILS_IS_MEDIA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA))
#define PHOTO_STREAM_UTILS_IS_MEDIA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_MEDIA))
#define PHOTO_STREAM_UTILS_MEDIA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA, PhotoStreamUtilsMediaClass))

typedef struct _PhotoStreamUtilsMedia PhotoStreamUtilsMedia;
typedef struct _PhotoStreamUtilsMediaClass PhotoStreamUtilsMediaClass;

#define PHOTO_STREAM_UTILS_TYPE_TAGGED_USER (photo_stream_utils_tagged_user_get_type ())
#define PHOTO_STREAM_UTILS_TAGGED_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_TAGGED_USER, PhotoStreamUtilsTaggedUser))
#define PHOTO_STREAM_UTILS_TAGGED_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_TAGGED_USER, PhotoStreamUtilsTaggedUserClass))
#define PHOTO_STREAM_UTILS_IS_TAGGED_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_TAGGED_USER))
#define PHOTO_STREAM_UTILS_IS_TAGGED_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_TAGGED_USER))
#define PHOTO_STREAM_UTILS_TAGGED_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_TAGGED_USER, PhotoStreamUtilsTaggedUserClass))

typedef struct _PhotoStreamUtilsTaggedUser PhotoStreamUtilsTaggedUser;
typedef struct _PhotoStreamUtilsTaggedUserClass PhotoStreamUtilsTaggedUserClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _PhotoStreamUtilsUserPrivate PhotoStreamUtilsUserPrivate;

#define PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP (photo_stream_utils_relationship_get_type ())
#define PHOTO_STREAM_UTILS_RELATIONSHIP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP, PhotoStreamUtilsRelationship))
#define PHOTO_STREAM_UTILS_RELATIONSHIP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP, PhotoStreamUtilsRelationshipClass))
#define PHOTO_STREAM_UTILS_IS_RELATIONSHIP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP))
#define PHOTO_STREAM_UTILS_IS_RELATIONSHIP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP))
#define PHOTO_STREAM_UTILS_RELATIONSHIP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP, PhotoStreamUtilsRelationshipClass))

typedef struct _PhotoStreamUtilsRelationship PhotoStreamUtilsRelationship;
typedef struct _PhotoStreamUtilsRelationshipClass PhotoStreamUtilsRelationshipClass;
#define _photo_stream_utils_user_unref0(var) ((var == NULL) ? NULL : (var = (photo_stream_utils_user_unref (var), NULL)))
typedef struct _PhotoStreamUtilsMediaPrivate PhotoStreamUtilsMediaPrivate;
typedef struct _PhotoStreamUtilsTaggedUserPrivate PhotoStreamUtilsTaggedUserPrivate;
#define _photo_stream_utils_tagged_user_unref0(var) ((var == NULL) ? NULL : (var = (photo_stream_utils_tagged_user_unref (var), NULL)))
#define _photo_stream_utils_comment_unref0(var) ((var == NULL) ? NULL : (var = (photo_stream_utils_comment_unref (var), NULL)))
typedef struct _PhotoStreamUtilsLocationPrivate PhotoStreamUtilsLocationPrivate;
typedef struct _PhotoStreamUtilsCommentPrivate PhotoStreamUtilsCommentPrivate;

#define PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY (photo_stream_utils_news_activity_get_type ())
#define PHOTO_STREAM_UTILS_NEWS_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY, PhotoStreamUtilsNewsActivity))
#define PHOTO_STREAM_UTILS_NEWS_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY, PhotoStreamUtilsNewsActivityClass))
#define PHOTO_STREAM_UTILS_IS_NEWS_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY))
#define PHOTO_STREAM_UTILS_IS_NEWS_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY))
#define PHOTO_STREAM_UTILS_NEWS_ACTIVITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY, PhotoStreamUtilsNewsActivityClass))

typedef struct _PhotoStreamUtilsNewsActivity PhotoStreamUtilsNewsActivity;
typedef struct _PhotoStreamUtilsNewsActivityClass PhotoStreamUtilsNewsActivityClass;
#define _photo_stream_utils_news_activity_unref0(var) ((var == NULL) ? NULL : (var = (photo_stream_utils_news_activity_unref (var), NULL)))
typedef struct _PhotoStreamUtilsNewsActivityPrivate PhotoStreamUtilsNewsActivityPrivate;

#define PHOTO_STREAM_UTILS_TYPE_HISTORY_ENTRY (photo_stream_utils_history_entry_get_type ())
#define PHOTO_STREAM_UTILS_HISTORY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_HISTORY_ENTRY, PhotoStreamUtilsHistoryEntry))
#define PHOTO_STREAM_UTILS_HISTORY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_HISTORY_ENTRY, PhotoStreamUtilsHistoryEntryClass))
#define PHOTO_STREAM_UTILS_IS_HISTORY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_HISTORY_ENTRY))
#define PHOTO_STREAM_UTILS_IS_HISTORY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_HISTORY_ENTRY))
#define PHOTO_STREAM_UTILS_HISTORY_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_HISTORY_ENTRY, PhotoStreamUtilsHistoryEntryClass))

typedef struct _PhotoStreamUtilsHistoryEntry PhotoStreamUtilsHistoryEntry;
typedef struct _PhotoStreamUtilsHistoryEntryClass PhotoStreamUtilsHistoryEntryClass;
#define _photo_stream_utils_history_entry_unref0(var) ((var == NULL) ? NULL : (var = (photo_stream_utils_history_entry_unref (var), NULL)))
typedef struct _PhotoStreamUtilsHistoryEntryPrivate PhotoStreamUtilsHistoryEntryPrivate;

struct _PhotoStreamUtilsMediaInfo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsMediaInfoPrivate * priv;
	gint type;
	GList* tags;
	gint64 commentsCount;
	GList* comments;
	gchar* filter;
	GDateTime* creationTime;
	PhotoStreamUtilsLocation* location;
	gchar* link;
	GList* likes;
	gint64 likesCount;
	PhotoStreamUtilsMedia* media;
	GList* taggedUsers;
	gchar* title;
	PhotoStreamUtilsUser* postedUser;
	gchar* id;
	gboolean didILikeThis;
};

struct _PhotoStreamUtilsMediaInfoClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsMediaInfo *self);
};

struct _PhotoStreamUtilsUser {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsUserPrivate * priv;
	gchar* username;
	gchar* profilePicture;
	gchar* fullName;
	gchar* id;
	gchar* website;
	gchar* bio;
	gint64 mediaCount;
	gint64 followers;
	gint64 followed;
	PhotoStreamUtilsRelationship* relationship;
};

struct _PhotoStreamUtilsUserClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsUser *self);
};

struct _PhotoStreamUtilsMedia {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsMediaPrivate * priv;
	gchar* url;
	gint64 width;
	gint64 height;
	gchar* previewUrl;
};

struct _PhotoStreamUtilsMediaClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsMedia *self);
};

struct _PhotoStreamUtilsTaggedUser {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsTaggedUserPrivate * priv;
	gdouble x;
	gdouble y;
	PhotoStreamUtilsUser* user;
};

struct _PhotoStreamUtilsTaggedUserClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsTaggedUser *self);
};

struct _PhotoStreamUtilsLocation {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsLocationPrivate * priv;
	gdouble latitude;
	gdouble longitude;
	gchar* id;
	gchar* name;
};

struct _PhotoStreamUtilsLocationClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsLocation *self);
};

struct _PhotoStreamUtilsComment {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsCommentPrivate * priv;
	GDateTime* creationTime;
	gchar* text;
	PhotoStreamUtilsUser* user;
	gchar* id;
};

struct _PhotoStreamUtilsCommentClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsComment *self);
};

struct _PhotoStreamUtilsNewsActivity {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsNewsActivityPrivate * priv;
	gchar* username;
	gchar* userProfilePicture;
	gchar* imagePicture;
	gchar* activityType;
	gchar* postId;
	GDateTime* time;
	gchar* comment;
};

struct _PhotoStreamUtilsNewsActivityClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsNewsActivity *self);
};

struct _PhotoStreamUtilsHistoryEntry {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsHistoryEntryPrivate * priv;
	gchar* type;
	gchar* id;
};

struct _PhotoStreamUtilsHistoryEntryClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsHistoryEntry *self);
};



gpointer photo_stream_utils_media_info_ref (gpointer instance);
void photo_stream_utils_media_info_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_media_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_media_info (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_media_info (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_media_info (const GValue* value);
GType photo_stream_utils_media_info_get_type (void) G_GNUC_CONST;
void printFeed (GList* list);
void printPost (PhotoStreamUtilsMediaInfo* post);
gpointer photo_stream_utils_comment_ref (gpointer instance);
void photo_stream_utils_comment_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_comment (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_comment (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_comment (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_comment (const GValue* value);
GType photo_stream_utils_comment_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_location_ref (gpointer instance);
void photo_stream_utils_location_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_location (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_location (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_location (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_location (const GValue* value);
GType photo_stream_utils_location_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_user_ref (gpointer instance);
void photo_stream_utils_user_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_user (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_user (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_user (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_user (const GValue* value);
GType photo_stream_utils_user_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_media_ref (gpointer instance);
void photo_stream_utils_media_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_media (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_media (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_media (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_media (const GValue* value);
GType photo_stream_utils_media_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_tagged_user_ref (gpointer instance);
void photo_stream_utils_tagged_user_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_tagged_user (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_tagged_user (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_tagged_user (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_tagged_user (const GValue* value);
GType photo_stream_utils_tagged_user_get_type (void) G_GNUC_CONST;
#define PHOTO_STREAM_MEDIA_TYPE_IMAGE 1
void printLocation (PhotoStreamUtilsLocation* location);
gpointer photo_stream_utils_relationship_ref (gpointer instance);
void photo_stream_utils_relationship_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_relationship (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_relationship (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_relationship (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_relationship (const GValue* value);
GType photo_stream_utils_relationship_get_type (void) G_GNUC_CONST;
void printComment (PhotoStreamUtilsComment* comment);
gpointer photo_stream_utils_news_activity_ref (gpointer instance);
void photo_stream_utils_news_activity_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_news_activity (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_news_activity (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_news_activity (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_news_activity (const GValue* value);
GType photo_stream_utils_news_activity_get_type (void) G_GNUC_CONST;
void printActivityList (GList* activityList);
void printActivity (PhotoStreamUtilsNewsActivity* activity);
gpointer photo_stream_utils_history_entry_ref (gpointer instance);
void photo_stream_utils_history_entry_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_history_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_history_entry (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_history_entry (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_history_entry (const GValue* value);
GType photo_stream_utils_history_entry_get_type (void) G_GNUC_CONST;
void printHistory (GList* history);
void printHistoryEntry (PhotoStreamUtilsHistoryEntry* entry);


static gpointer _photo_stream_utils_media_info_ref0 (gpointer self) {
#line 5 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	return self ? photo_stream_utils_media_info_ref (self) : NULL;
#line 336 "Debug.c"
}


void printFeed (GList* list) {
	GList* _tmp0_ = NULL;
#line 5 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp0_ = list;
#line 344 "Debug.c"
	{
		GList* post_collection = NULL;
		GList* post_it = NULL;
#line 5 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		post_collection = _tmp0_;
#line 5 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		for (post_it = post_collection; post_it != NULL; post_it = post_it->next) {
#line 352 "Debug.c"
			PhotoStreamUtilsMediaInfo* _tmp1_ = NULL;
			PhotoStreamUtilsMediaInfo* post = NULL;
#line 5 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			_tmp1_ = _photo_stream_utils_media_info_ref0 ((PhotoStreamUtilsMediaInfo*) post_it->data);
#line 5 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			post = _tmp1_;
#line 359 "Debug.c"
			{
				PhotoStreamUtilsMediaInfo* _tmp2_ = NULL;
#line 6 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp2_ = post;
#line 6 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				printPost (_tmp2_);
#line 5 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_photo_stream_utils_media_info_unref0 (post);
#line 368 "Debug.c"
			}
		}
	}
}


static gpointer _photo_stream_utils_user_ref0 (gpointer self) {
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	return self ? photo_stream_utils_user_ref (self) : NULL;
#line 378 "Debug.c"
}


static gpointer _photo_stream_utils_tagged_user_ref0 (gpointer self) {
#line 36 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	return self ? photo_stream_utils_tagged_user_ref (self) : NULL;
#line 385 "Debug.c"
}


static gpointer _photo_stream_utils_comment_ref0 (gpointer self) {
#line 48 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	return self ? photo_stream_utils_comment_ref (self) : NULL;
#line 392 "Debug.c"
}


void printPost (PhotoStreamUtilsMediaInfo* post) {
	PhotoStreamUtilsMediaInfo* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
	const gchar* _tmp4_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	const gchar* _tmp7_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp8_ = NULL;
	PhotoStreamUtilsLocation* _tmp9_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp10_ = NULL;
	PhotoStreamUtilsLocation* _tmp11_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp14_ = NULL;
	gint64 _tmp15_ = 0LL;
	PhotoStreamUtilsMediaInfo* _tmp16_ = NULL;
	GList* _tmp17_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp27_ = NULL;
	PhotoStreamUtilsMedia* _tmp28_ = NULL;
	const gchar* _tmp29_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp30_ = NULL;
	PhotoStreamUtilsMedia* _tmp31_ = NULL;
	gint64 _tmp32_ = 0LL;
	PhotoStreamUtilsMediaInfo* _tmp33_ = NULL;
	PhotoStreamUtilsMedia* _tmp34_ = NULL;
	gint64 _tmp35_ = 0LL;
	PhotoStreamUtilsMediaInfo* _tmp36_ = NULL;
	GList* _tmp37_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp55_ = NULL;
	GList* _tmp56_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp59_ = NULL;
	const gchar* _tmp60_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp61_ = NULL;
	GDateTime* _tmp62_ = NULL;
	const gchar* _tmp63_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp64_ = NULL;
	const gchar* _tmp65_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp68_ = NULL;
	PhotoStreamUtilsUser* _tmp69_ = NULL;
	const gchar* _tmp70_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp71_ = NULL;
	PhotoStreamUtilsUser* _tmp72_ = NULL;
	const gchar* _tmp73_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp74_ = NULL;
	PhotoStreamUtilsUser* _tmp75_ = NULL;
	const gchar* _tmp76_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp77_ = NULL;
	PhotoStreamUtilsUser* _tmp78_ = NULL;
	const gchar* _tmp79_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp80_ = NULL;
	PhotoStreamUtilsUser* _tmp81_ = NULL;
	const gchar* _tmp82_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp83_ = NULL;
	PhotoStreamUtilsUser* _tmp84_ = NULL;
	const gchar* _tmp85_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp86_ = NULL;
	const gchar* _tmp87_ = NULL;
	const gchar* _tmp88_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp89_ = NULL;
	gboolean _tmp90_ = FALSE;
#line 10 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_return_if_fail (post != NULL);
#line 12 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Tags: ");
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp0_ = post;
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp1_ = _tmp0_->tags;
#line 462 "Debug.c"
	{
		GList* tag_collection = NULL;
		GList* tag_it = NULL;
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		tag_collection = _tmp1_;
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		for (tag_it = tag_collection; tag_it != NULL; tag_it = tag_it->next) {
#line 470 "Debug.c"
			gchar* _tmp2_ = NULL;
			gchar* tag = NULL;
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			_tmp2_ = g_strdup ((const gchar*) tag_it->data);
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			tag = _tmp2_;
#line 477 "Debug.c"
			{
				const gchar* _tmp3_ = NULL;
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp3_ = tag;
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("%s ", _tmp3_);
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_g_free0 (tag);
#line 486 "Debug.c"
			}
		}
	}
#line 16 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp5_ = post;
#line 16 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp6_ = _tmp5_->type;
#line 16 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	if (_tmp6_ == PHOTO_STREAM_MEDIA_TYPE_IMAGE) {
#line 16 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp4_ = "image";
#line 498 "Debug.c"
	} else {
#line 16 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp4_ = "video";
#line 502 "Debug.c"
	}
#line 16 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Type: %s\n", _tmp4_);
#line 17 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp8_ = post;
#line 17 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp9_ = _tmp8_->location;
#line 17 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	if (_tmp9_ == NULL) {
#line 17 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp7_ = "(null)";
#line 514 "Debug.c"
	} else {
#line 17 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp7_ = "";
#line 518 "Debug.c"
	}
#line 17 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Location: %s\n", _tmp7_);
#line 18 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp10_ = post;
#line 18 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp11_ = _tmp10_->location;
#line 18 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	if (_tmp11_ != NULL) {
#line 528 "Debug.c"
		PhotoStreamUtilsMediaInfo* _tmp12_ = NULL;
		PhotoStreamUtilsLocation* _tmp13_ = NULL;
#line 19 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp12_ = post;
#line 19 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp13_ = _tmp12_->location;
#line 19 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		printLocation (_tmp13_);
#line 537 "Debug.c"
	}
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp14_ = post;
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp15_ = _tmp14_->likesCount;
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Likes: %" G_GINT64_MODIFIER "d\n ", _tmp15_);
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp16_ = post;
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp17_ = _tmp16_->likes;
#line 549 "Debug.c"
	{
		GList* user_collection = NULL;
		GList* user_it = NULL;
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		user_collection = _tmp17_;
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		for (user_it = user_collection; user_it != NULL; user_it = user_it->next) {
#line 557 "Debug.c"
			PhotoStreamUtilsUser* _tmp18_ = NULL;
			PhotoStreamUtilsUser* user = NULL;
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			_tmp18_ = _photo_stream_utils_user_ref0 ((PhotoStreamUtilsUser*) user_it->data);
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			user = _tmp18_;
#line 564 "Debug.c"
			{
				PhotoStreamUtilsUser* _tmp19_ = NULL;
				const gchar* _tmp20_ = NULL;
				PhotoStreamUtilsUser* _tmp21_ = NULL;
				const gchar* _tmp22_ = NULL;
				PhotoStreamUtilsUser* _tmp23_ = NULL;
				const gchar* _tmp24_ = NULL;
				PhotoStreamUtilsUser* _tmp25_ = NULL;
				const gchar* _tmp26_ = NULL;
#line 24 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp19_ = user;
#line 24 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp20_ = _tmp19_->username;
#line 24 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("\tusername: %s\n", _tmp20_);
#line 25 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp21_ = user;
#line 25 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp22_ = _tmp21_->profilePicture;
#line 25 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("\tprofilePicture: %s\n", _tmp22_);
#line 26 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp23_ = user;
#line 26 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp24_ = _tmp23_->id;
#line 26 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("\tid: %s\n", _tmp24_);
#line 27 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp25_ = user;
#line 27 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp26_ = _tmp25_->fullName;
#line 27 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("\tfullName: %s\n\n", _tmp26_);
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_photo_stream_utils_user_unref0 (user);
#line 600 "Debug.c"
			}
		}
	}
#line 30 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Image: \n");
#line 31 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp27_ = post;
#line 31 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp28_ = _tmp27_->media;
#line 31 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp29_ = _tmp28_->url;
#line 31 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\turl: %s\n", _tmp29_);
#line 32 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp30_ = post;
#line 32 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp31_ = _tmp30_->media;
#line 32 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp32_ = _tmp31_->width;
#line 32 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\twidth: %" G_GINT64_MODIFIER "d\n", _tmp32_);
#line 33 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp33_ = post;
#line 33 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp34_ = _tmp33_->media;
#line 33 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp35_ = _tmp34_->height;
#line 33 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\theight: %" G_GINT64_MODIFIER "d\n", _tmp35_);
#line 35 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Users in photo: \n");
#line 36 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp36_ = post;
#line 36 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp37_ = _tmp36_->taggedUsers;
#line 636 "Debug.c"
	{
		GList* user_collection = NULL;
		GList* user_it = NULL;
#line 36 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		user_collection = _tmp37_;
#line 36 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		for (user_it = user_collection; user_it != NULL; user_it = user_it->next) {
#line 644 "Debug.c"
			PhotoStreamUtilsTaggedUser* _tmp38_ = NULL;
			PhotoStreamUtilsTaggedUser* user = NULL;
#line 36 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			_tmp38_ = _photo_stream_utils_tagged_user_ref0 ((PhotoStreamUtilsTaggedUser*) user_it->data);
#line 36 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			user = _tmp38_;
#line 651 "Debug.c"
			{
				PhotoStreamUtilsTaggedUser* _tmp39_ = NULL;
				gdouble _tmp40_ = 0.0;
				PhotoStreamUtilsTaggedUser* _tmp41_ = NULL;
				gdouble _tmp42_ = 0.0;
				PhotoStreamUtilsTaggedUser* _tmp43_ = NULL;
				PhotoStreamUtilsUser* _tmp44_ = NULL;
				const gchar* _tmp45_ = NULL;
				PhotoStreamUtilsTaggedUser* _tmp46_ = NULL;
				PhotoStreamUtilsUser* _tmp47_ = NULL;
				const gchar* _tmp48_ = NULL;
				PhotoStreamUtilsTaggedUser* _tmp49_ = NULL;
				PhotoStreamUtilsUser* _tmp50_ = NULL;
				const gchar* _tmp51_ = NULL;
				PhotoStreamUtilsTaggedUser* _tmp52_ = NULL;
				PhotoStreamUtilsUser* _tmp53_ = NULL;
				const gchar* _tmp54_ = NULL;
#line 38 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp39_ = user;
#line 38 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp40_ = _tmp39_->x;
#line 38 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp41_ = user;
#line 38 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp42_ = _tmp41_->y;
#line 38 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("\tPosition: %f %f\n", _tmp40_, _tmp42_);
#line 39 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("\tUser: \n");
#line 40 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp43_ = user;
#line 40 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp44_ = _tmp43_->user;
#line 40 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp45_ = _tmp44_->username;
#line 40 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("\t\tusername: %s\n", _tmp45_);
#line 41 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp46_ = user;
#line 41 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp47_ = _tmp46_->user;
#line 41 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp48_ = _tmp47_->profilePicture;
#line 41 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("\t\tprofilePicture: %s\n", _tmp48_);
#line 42 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp49_ = user;
#line 42 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp50_ = _tmp49_->user;
#line 42 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp51_ = _tmp50_->id;
#line 42 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("\t\tid: %s\n", _tmp51_);
#line 43 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp52_ = user;
#line 43 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp53_ = _tmp52_->user;
#line 43 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp54_ = _tmp53_->fullName;
#line 43 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				g_print ("\t\tfullName: %s\n\n", _tmp54_);
#line 36 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_photo_stream_utils_tagged_user_unref0 (user);
#line 715 "Debug.c"
			}
		}
	}
#line 47 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\nComments:\n ");
#line 48 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp55_ = post;
#line 48 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp56_ = _tmp55_->comments;
#line 725 "Debug.c"
	{
		GList* comment_collection = NULL;
		GList* comment_it = NULL;
#line 48 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		comment_collection = _tmp56_;
#line 48 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		for (comment_it = comment_collection; comment_it != NULL; comment_it = comment_it->next) {
#line 733 "Debug.c"
			PhotoStreamUtilsComment* _tmp57_ = NULL;
			PhotoStreamUtilsComment* comment = NULL;
#line 48 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			_tmp57_ = _photo_stream_utils_comment_ref0 ((PhotoStreamUtilsComment*) comment_it->data);
#line 48 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			comment = _tmp57_;
#line 740 "Debug.c"
			{
				PhotoStreamUtilsComment* _tmp58_ = NULL;
#line 49 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp58_ = comment;
#line 49 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				printComment (_tmp58_);
#line 48 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_photo_stream_utils_comment_unref0 (comment);
#line 749 "Debug.c"
			}
		}
	}
#line 51 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp59_ = post;
#line 51 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp60_ = _tmp59_->filter;
#line 51 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Filter: %s\n", _tmp60_);
#line 52 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp61_ = post;
#line 52 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp62_ = _tmp61_->creationTime;
#line 52 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Creation time: %" G_GINT64_MODIFIER "d\n", _tmp62_);
#line 53 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Tagged users: \n");
#line 54 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp64_ = post;
#line 54 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp65_ = _tmp64_->title;
#line 54 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	if (g_strcmp0 (_tmp65_, "") == 0) {
#line 54 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp63_ = "<no title>";
#line 775 "Debug.c"
	} else {
		PhotoStreamUtilsMediaInfo* _tmp66_ = NULL;
		const gchar* _tmp67_ = NULL;
#line 54 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp66_ = post;
#line 54 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp67_ = _tmp66_->title;
#line 54 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp63_ = _tmp67_;
#line 785 "Debug.c"
	}
#line 54 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Title: %s\n", _tmp63_);
#line 55 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("User: \n");
#line 57 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp68_ = post;
#line 57 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp69_ = _tmp68_->postedUser;
#line 57 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp70_ = _tmp69_->username;
#line 57 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tusername: %s\n", _tmp70_);
#line 58 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp71_ = post;
#line 58 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp72_ = _tmp71_->postedUser;
#line 58 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp73_ = _tmp72_->profilePicture;
#line 58 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tprofilePicture: %s\n", _tmp73_);
#line 59 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp74_ = post;
#line 59 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp75_ = _tmp74_->postedUser;
#line 59 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp76_ = _tmp75_->id;
#line 59 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tid: %s\n", _tmp76_);
#line 60 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp77_ = post;
#line 60 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp78_ = _tmp77_->postedUser;
#line 60 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp79_ = _tmp78_->fullName;
#line 60 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tfullName: %s\n\n", _tmp79_);
#line 61 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp80_ = post;
#line 61 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp81_ = _tmp80_->postedUser;
#line 61 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp82_ = _tmp81_->bio;
#line 61 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tbio: %s\n", _tmp82_);
#line 62 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp83_ = post;
#line 62 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp84_ = _tmp83_->postedUser;
#line 62 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp85_ = _tmp84_->website;
#line 62 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\twebsite: %s\n\n", _tmp85_);
#line 64 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp86_ = post;
#line 64 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp87_ = _tmp86_->id;
#line 64 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("id: %s\n", _tmp87_);
#line 65 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp89_ = post;
#line 65 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp90_ = _tmp89_->didILikeThis;
#line 65 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	if (_tmp90_) {
#line 65 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp88_ = "true";
#line 853 "Debug.c"
	} else {
#line 65 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		_tmp88_ = "false";
#line 857 "Debug.c"
	}
#line 65 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("didILikeThis: %s\n\n", _tmp88_);
#line 861 "Debug.c"
}


void printLocation (PhotoStreamUtilsLocation* location) {
	PhotoStreamUtilsLocation* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	PhotoStreamUtilsLocation* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	PhotoStreamUtilsLocation* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	PhotoStreamUtilsLocation* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
#line 68 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_return_if_fail (location != NULL);
#line 70 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp0_ = location;
#line 70 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp1_ = _tmp0_->latitude;
#line 70 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tLatitude: %f\n", _tmp1_);
#line 71 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp2_ = location;
#line 71 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp3_ = _tmp2_->longitude;
#line 71 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tlongitude: %f\n", _tmp3_);
#line 72 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp4_ = location;
#line 72 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp5_ = _tmp4_->id;
#line 72 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tid: %" G_GINT64_MODIFIER "d\n", _tmp5_);
#line 73 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp6_ = location;
#line 73 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp7_ = _tmp6_->name;
#line 73 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tname: %s\n\n", _tmp7_);
#line 900 "Debug.c"
}


void printComment (PhotoStreamUtilsComment* comment) {
	PhotoStreamUtilsComment* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	PhotoStreamUtilsComment* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	PhotoStreamUtilsComment* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	PhotoStreamUtilsComment* _tmp6_ = NULL;
	PhotoStreamUtilsUser* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	PhotoStreamUtilsComment* _tmp9_ = NULL;
	PhotoStreamUtilsUser* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	PhotoStreamUtilsComment* _tmp12_ = NULL;
	PhotoStreamUtilsUser* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	PhotoStreamUtilsComment* _tmp15_ = NULL;
	PhotoStreamUtilsUser* _tmp16_ = NULL;
	const gchar* _tmp17_ = NULL;
#line 76 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_return_if_fail (comment != NULL);
#line 78 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp0_ = comment;
#line 78 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp1_ = _tmp0_->creationTime;
#line 78 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tCreation time: %" G_GINT64_MODIFIER "d\n", _tmp1_);
#line 79 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp2_ = comment;
#line 79 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp3_ = _tmp2_->text;
#line 79 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tText: %s\n", _tmp3_);
#line 80 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp4_ = comment;
#line 80 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp5_ = _tmp4_->id;
#line 80 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tComment ID: %" G_GINT64_MODIFIER "d\n", _tmp5_);
#line 81 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\tUser:\n");
#line 82 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp6_ = comment;
#line 82 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp7_ = _tmp6_->user;
#line 82 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp8_ = _tmp7_->username;
#line 82 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\t\tusername: %s\n", _tmp8_);
#line 83 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp9_ = comment;
#line 83 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp10_ = _tmp9_->user;
#line 83 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp11_ = _tmp10_->profilePicture;
#line 83 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\t\tprofilePicture: %s\n", _tmp11_);
#line 84 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp12_ = comment;
#line 84 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp13_ = _tmp12_->user;
#line 84 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp14_ = _tmp13_->id;
#line 84 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\t\tid: %" G_GINT64_MODIFIER "d\n", _tmp14_);
#line 85 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp15_ = comment;
#line 85 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp16_ = _tmp15_->user;
#line 85 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp17_ = _tmp16_->fullName;
#line 85 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("\t\tfullName: %s\n\n", _tmp17_);
#line 977 "Debug.c"
}


static gpointer _photo_stream_utils_news_activity_ref0 (gpointer self) {
#line 90 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	return self ? photo_stream_utils_news_activity_ref (self) : NULL;
#line 984 "Debug.c"
}


void printActivityList (GList* activityList) {
	GList* _tmp0_ = NULL;
#line 90 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp0_ = activityList;
#line 992 "Debug.c"
	{
		GList* activity_collection = NULL;
		GList* activity_it = NULL;
#line 90 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		activity_collection = _tmp0_;
#line 90 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		for (activity_it = activity_collection; activity_it != NULL; activity_it = activity_it->next) {
#line 1000 "Debug.c"
			PhotoStreamUtilsNewsActivity* _tmp1_ = NULL;
			PhotoStreamUtilsNewsActivity* activity = NULL;
#line 90 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			_tmp1_ = _photo_stream_utils_news_activity_ref0 ((PhotoStreamUtilsNewsActivity*) activity_it->data);
#line 90 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			activity = _tmp1_;
#line 1007 "Debug.c"
			{
				PhotoStreamUtilsNewsActivity* _tmp2_ = NULL;
#line 91 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp2_ = activity;
#line 91 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				printActivity (_tmp2_);
#line 90 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_photo_stream_utils_news_activity_unref0 (activity);
#line 1016 "Debug.c"
			}
		}
	}
}


void printActivity (PhotoStreamUtilsNewsActivity* activity) {
	PhotoStreamUtilsNewsActivity* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	PhotoStreamUtilsNewsActivity* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	PhotoStreamUtilsNewsActivity* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	PhotoStreamUtilsNewsActivity* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	PhotoStreamUtilsNewsActivity* _tmp8_ = NULL;
	GDateTime* _tmp9_ = NULL;
	PhotoStreamUtilsNewsActivity* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
#line 94 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_return_if_fail (activity != NULL);
#line 96 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp0_ = activity;
#line 96 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp1_ = _tmp0_->activityType;
#line 96 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Type: %s\n", _tmp1_);
#line 97 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp2_ = activity;
#line 97 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp3_ = _tmp2_->username;
#line 97 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Username: %s\n", _tmp3_);
#line 98 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp4_ = activity;
#line 98 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp5_ = _tmp4_->userProfilePicture;
#line 98 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("User profile pic: %s\n", _tmp5_);
#line 99 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp6_ = activity;
#line 99 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp7_ = _tmp6_->postId;
#line 99 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Post id: %s\n", _tmp7_);
#line 100 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp8_ = activity;
#line 100 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp9_ = _tmp8_->time;
#line 100 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Date: %" G_GINT64_MODIFIER "d\n", _tmp9_);
#line 101 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp10_ = activity;
#line 101 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp11_ = _tmp10_->comment;
#line 101 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Comment: %s\n\n", _tmp11_);
#line 1074 "Debug.c"
}


static gpointer _photo_stream_utils_history_entry_ref0 (gpointer self) {
#line 107 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	return self ? photo_stream_utils_history_entry_ref (self) : NULL;
#line 1081 "Debug.c"
}


void printHistory (GList* history) {
	GList* _tmp0_ = NULL;
#line 106 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("===\n");
#line 107 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp0_ = history;
#line 1091 "Debug.c"
	{
		GList* entry_collection = NULL;
		GList* entry_it = NULL;
#line 107 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		entry_collection = _tmp0_;
#line 107 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
		for (entry_it = entry_collection; entry_it != NULL; entry_it = entry_it->next) {
#line 1099 "Debug.c"
			PhotoStreamUtilsHistoryEntry* _tmp1_ = NULL;
			PhotoStreamUtilsHistoryEntry* entry = NULL;
#line 107 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			_tmp1_ = _photo_stream_utils_history_entry_ref0 ((PhotoStreamUtilsHistoryEntry*) entry_it->data);
#line 107 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
			entry = _tmp1_;
#line 1106 "Debug.c"
			{
				PhotoStreamUtilsHistoryEntry* _tmp2_ = NULL;
#line 108 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_tmp2_ = entry;
#line 108 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				printHistoryEntry (_tmp2_);
#line 107 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
				_photo_stream_utils_history_entry_unref0 (entry);
#line 1115 "Debug.c"
			}
		}
	}
#line 109 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("===\n");
#line 1121 "Debug.c"
}


void printHistoryEntry (PhotoStreamUtilsHistoryEntry* entry) {
	PhotoStreamUtilsHistoryEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	PhotoStreamUtilsHistoryEntry* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
#line 112 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_return_if_fail (entry != NULL);
#line 114 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp0_ = entry;
#line 114 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp1_ = _tmp0_->type;
#line 114 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Type: %s\n", _tmp1_);
#line 115 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp2_ = entry;
#line 115 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	_tmp3_ = _tmp2_->id;
#line 115 "/all/Documents/Programming/vala/photostream/src/Utils/Debug.vala"
	g_print ("Id: %s\n", _tmp3_);
#line 1144 "Debug.c"
}



