/* NewsObjects.c generated by valac 0.26.1.9-22126, the Vala compiler
 * generated from NewsObjects.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY (photo_stream_utils_news_activity_get_type ())
#define PHOTO_STREAM_UTILS_NEWS_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY, PhotoStreamUtilsNewsActivity))
#define PHOTO_STREAM_UTILS_NEWS_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY, PhotoStreamUtilsNewsActivityClass))
#define PHOTO_STREAM_UTILS_IS_NEWS_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY))
#define PHOTO_STREAM_UTILS_IS_NEWS_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY))
#define PHOTO_STREAM_UTILS_NEWS_ACTIVITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY, PhotoStreamUtilsNewsActivityClass))

typedef struct _PhotoStreamUtilsNewsActivity PhotoStreamUtilsNewsActivity;
typedef struct _PhotoStreamUtilsNewsActivityClass PhotoStreamUtilsNewsActivityClass;
typedef struct _PhotoStreamUtilsNewsActivityPrivate PhotoStreamUtilsNewsActivityPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
typedef struct _PhotoStreamUtilsParamSpecNewsActivity PhotoStreamUtilsParamSpecNewsActivity;

struct _PhotoStreamUtilsNewsActivity {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsNewsActivityPrivate * priv;
	gchar* username;
	gchar* userProfilePicture;
	gchar* imagePicture;
	gchar* activityType;
	gchar* postId;
	GDateTime* time;
	gchar* comment;
};

struct _PhotoStreamUtilsNewsActivityClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsNewsActivity *self);
};

struct _PhotoStreamUtilsParamSpecNewsActivity {
	GParamSpec parent_instance;
};


static gpointer photo_stream_utils_news_activity_parent_class = NULL;

gpointer photo_stream_utils_news_activity_ref (gpointer instance);
void photo_stream_utils_news_activity_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_news_activity (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_news_activity (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_news_activity (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_news_activity (const GValue* value);
GType photo_stream_utils_news_activity_get_type (void) G_GNUC_CONST;
enum  {
	PHOTO_STREAM_UTILS_NEWS_ACTIVITY_DUMMY_PROPERTY
};
PhotoStreamUtilsNewsActivity* photo_stream_utils_news_activity_new (void);
PhotoStreamUtilsNewsActivity* photo_stream_utils_news_activity_construct (GType object_type);
static void photo_stream_utils_news_activity_finalize (PhotoStreamUtilsNewsActivity* obj);


PhotoStreamUtilsNewsActivity* photo_stream_utils_news_activity_construct (GType object_type) {
	PhotoStreamUtilsNewsActivity* self = NULL;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	self = (PhotoStreamUtilsNewsActivity*) g_type_create_instance (object_type);
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	return self;
#line 73 "NewsObjects.c"
}


PhotoStreamUtilsNewsActivity* photo_stream_utils_news_activity_new (void) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	return photo_stream_utils_news_activity_construct (PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY);
#line 80 "NewsObjects.c"
}


static void photo_stream_utils_value_news_activity_init (GValue* value) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	value->data[0].v_pointer = NULL;
#line 87 "NewsObjects.c"
}


static void photo_stream_utils_value_news_activity_free_value (GValue* value) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	if (value->data[0].v_pointer) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		photo_stream_utils_news_activity_unref (value->data[0].v_pointer);
#line 96 "NewsObjects.c"
	}
}


static void photo_stream_utils_value_news_activity_copy_value (const GValue* src_value, GValue* dest_value) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	if (src_value->data[0].v_pointer) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		dest_value->data[0].v_pointer = photo_stream_utils_news_activity_ref (src_value->data[0].v_pointer);
#line 106 "NewsObjects.c"
	} else {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		dest_value->data[0].v_pointer = NULL;
#line 110 "NewsObjects.c"
	}
}


static gpointer photo_stream_utils_value_news_activity_peek_pointer (const GValue* value) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	return value->data[0].v_pointer;
#line 118 "NewsObjects.c"
}


static gchar* photo_stream_utils_value_news_activity_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	if (collect_values[0].v_pointer) {
#line 125 "NewsObjects.c"
		PhotoStreamUtilsNewsActivity* object;
		object = collect_values[0].v_pointer;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		if (object->parent_instance.g_class == NULL) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 132 "NewsObjects.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 136 "NewsObjects.c"
		}
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		value->data[0].v_pointer = photo_stream_utils_news_activity_ref (object);
#line 140 "NewsObjects.c"
	} else {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		value->data[0].v_pointer = NULL;
#line 144 "NewsObjects.c"
	}
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	return NULL;
#line 148 "NewsObjects.c"
}


static gchar* photo_stream_utils_value_news_activity_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	PhotoStreamUtilsNewsActivity** object_p;
	object_p = collect_values[0].v_pointer;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	if (!object_p) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 159 "NewsObjects.c"
	}
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	if (!value->data[0].v_pointer) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		*object_p = NULL;
#line 165 "NewsObjects.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		*object_p = value->data[0].v_pointer;
#line 169 "NewsObjects.c"
	} else {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		*object_p = photo_stream_utils_news_activity_ref (value->data[0].v_pointer);
#line 173 "NewsObjects.c"
	}
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	return NULL;
#line 177 "NewsObjects.c"
}


GParamSpec* photo_stream_utils_param_spec_news_activity (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	PhotoStreamUtilsParamSpecNewsActivity* spec;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	g_return_val_if_fail (g_type_is_a (object_type, PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY), NULL);
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	return G_PARAM_SPEC (spec);
#line 191 "NewsObjects.c"
}


gpointer photo_stream_utils_value_get_news_activity (const GValue* value) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY), NULL);
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	return value->data[0].v_pointer;
#line 200 "NewsObjects.c"
}


void photo_stream_utils_value_set_news_activity (GValue* value, gpointer v_object) {
	PhotoStreamUtilsNewsActivity* old;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY));
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	old = value->data[0].v_pointer;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	if (v_object) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY));
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		value->data[0].v_pointer = v_object;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		photo_stream_utils_news_activity_ref (value->data[0].v_pointer);
#line 220 "NewsObjects.c"
	} else {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		value->data[0].v_pointer = NULL;
#line 224 "NewsObjects.c"
	}
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	if (old) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		photo_stream_utils_news_activity_unref (old);
#line 230 "NewsObjects.c"
	}
}


void photo_stream_utils_value_take_news_activity (GValue* value, gpointer v_object) {
	PhotoStreamUtilsNewsActivity* old;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY));
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	old = value->data[0].v_pointer;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	if (v_object) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY));
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		value->data[0].v_pointer = v_object;
#line 249 "NewsObjects.c"
	} else {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		value->data[0].v_pointer = NULL;
#line 253 "NewsObjects.c"
	}
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	if (old) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		photo_stream_utils_news_activity_unref (old);
#line 259 "NewsObjects.c"
	}
}


static void photo_stream_utils_news_activity_class_init (PhotoStreamUtilsNewsActivityClass * klass) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	photo_stream_utils_news_activity_parent_class = g_type_class_peek_parent (klass);
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	((PhotoStreamUtilsNewsActivityClass *) klass)->finalize = photo_stream_utils_news_activity_finalize;
#line 269 "NewsObjects.c"
}


static void photo_stream_utils_news_activity_instance_init (PhotoStreamUtilsNewsActivity * self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	_tmp0_ = g_strdup ("");
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	self->imagePicture = _tmp0_;
#line 9 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	_tmp1_ = g_strdup ("");
#line 9 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	self->postId = _tmp1_;
#line 11 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	_tmp2_ = g_strdup ("");
#line 11 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	self->comment = _tmp2_;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	self->ref_count = 1;
#line 291 "NewsObjects.c"
}


static void photo_stream_utils_news_activity_finalize (PhotoStreamUtilsNewsActivity* obj) {
	PhotoStreamUtilsNewsActivity * self;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY, PhotoStreamUtilsNewsActivity);
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	g_signal_handlers_destroy (self);
#line 5 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	_g_free0 (self->username);
#line 6 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	_g_free0 (self->userProfilePicture);
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	_g_free0 (self->imagePicture);
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	_g_free0 (self->activityType);
#line 9 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	_g_free0 (self->postId);
#line 10 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	_g_date_time_unref0 (self->time);
#line 11 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	_g_free0 (self->comment);
#line 315 "NewsObjects.c"
}


GType photo_stream_utils_news_activity_get_type (void) {
	static volatile gsize photo_stream_utils_news_activity_type_id__volatile = 0;
	if (g_once_init_enter (&photo_stream_utils_news_activity_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { photo_stream_utils_value_news_activity_init, photo_stream_utils_value_news_activity_free_value, photo_stream_utils_value_news_activity_copy_value, photo_stream_utils_value_news_activity_peek_pointer, "p", photo_stream_utils_value_news_activity_collect_value, "p", photo_stream_utils_value_news_activity_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PhotoStreamUtilsNewsActivityClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) photo_stream_utils_news_activity_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PhotoStreamUtilsNewsActivity), 0, (GInstanceInitFunc) photo_stream_utils_news_activity_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType photo_stream_utils_news_activity_type_id;
		photo_stream_utils_news_activity_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PhotoStreamUtilsNewsActivity", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&photo_stream_utils_news_activity_type_id__volatile, photo_stream_utils_news_activity_type_id);
	}
	return photo_stream_utils_news_activity_type_id__volatile;
}


gpointer photo_stream_utils_news_activity_ref (gpointer instance) {
	PhotoStreamUtilsNewsActivity* self;
	self = instance;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	g_atomic_int_inc (&self->ref_count);
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	return instance;
#line 340 "NewsObjects.c"
}


void photo_stream_utils_news_activity_unref (gpointer instance) {
	PhotoStreamUtilsNewsActivity* self;
	self = instance;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		PHOTO_STREAM_UTILS_NEWS_ACTIVITY_GET_CLASS (self)->finalize (self);
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/NewsObjects.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 353 "NewsObjects.c"
	}
}



