/* TagsWrapping.c generated by valac 0.26.1.9-22126, the Vala compiler
 * generated from TagsWrapping.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))



gchar* wrapInTags (const gchar* original);
static gboolean ___lambda10_ (GMatchInfo* mi, GString* s);
static gboolean ____lambda10__gregex_eval_callback (GMatchInfo* match_info, GString* _result_, gpointer self);
static gboolean ___lambda11_ (GMatchInfo* mi, GString* s);
static gboolean ____lambda11__gregex_eval_callback (GMatchInfo* match_info, GString* _result_, gpointer self);
static gboolean ___lambda12_ (GMatchInfo* mi, GString* s);
static gboolean ____lambda12__gregex_eval_callback (GMatchInfo* match_info, GString* _result_, gpointer self);


static gboolean ___lambda10_ (GMatchInfo* mi, GString* s) {
	gboolean result = FALSE;
	GString* _tmp0_ = NULL;
	GMatchInfo* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GMatchInfo* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	g_return_val_if_fail (mi != NULL, FALSE);
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	g_return_val_if_fail (s != NULL, FALSE);
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp0_ = s;
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp1_ = mi;
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp2_ = g_match_info_fetch (_tmp1_, 0);
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp3_ = _tmp2_;
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp4_ = mi;
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp5_ = g_match_info_fetch (_tmp4_, 0);
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp6_ = _tmp5_;
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	g_string_append_printf (_tmp0_, "<a href=\"%s\">%s</a>", _tmp3_, _tmp6_);
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_g_free0 (_tmp6_);
#line 8 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_g_free0 (_tmp3_);
#line 9 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	result = FALSE;
#line 9 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	return result;
#line 63 "TagsWrapping.c"
}


static gboolean ____lambda10__gregex_eval_callback (GMatchInfo* match_info, GString* _result_, gpointer self) {
	gboolean result;
	result = ___lambda10_ (match_info, _result_);
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	return result;
#line 72 "TagsWrapping.c"
}


static gboolean ___lambda11_ (GMatchInfo* mi, GString* s) {
	gboolean result = FALSE;
	GString* _tmp0_ = NULL;
	GMatchInfo* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GMatchInfo* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	g_return_val_if_fail (mi != NULL, FALSE);
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	g_return_val_if_fail (s != NULL, FALSE);
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp0_ = s;
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp1_ = mi;
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp2_ = g_match_info_fetch (_tmp1_, 0);
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp3_ = _tmp2_;
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp4_ = mi;
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp5_ = g_match_info_fetch (_tmp4_, 0);
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp6_ = _tmp5_;
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	g_string_append_printf (_tmp0_, "<a href=\"%s\">%s</a>", _tmp3_, _tmp6_);
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_g_free0 (_tmp6_);
#line 14 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_g_free0 (_tmp3_);
#line 15 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	result = FALSE;
#line 15 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	return result;
#line 113 "TagsWrapping.c"
}


static gboolean ____lambda11__gregex_eval_callback (GMatchInfo* match_info, GString* _result_, gpointer self) {
	gboolean result;
	result = ___lambda11_ (match_info, _result_);
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	return result;
#line 122 "TagsWrapping.c"
}


static gboolean ___lambda12_ (GMatchInfo* mi, GString* s) {
	gboolean result = FALSE;
	GString* _tmp0_ = NULL;
	GMatchInfo* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GMatchInfo* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	g_return_val_if_fail (mi != NULL, FALSE);
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	g_return_val_if_fail (s != NULL, FALSE);
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp0_ = s;
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp1_ = mi;
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp2_ = g_match_info_fetch (_tmp1_, 0);
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp3_ = _tmp2_;
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp4_ = mi;
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp5_ = g_match_info_fetch (_tmp4_, 0);
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp6_ = _tmp5_;
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	g_string_append_printf (_tmp0_, "<a href=\"%s\">%s</a>", _tmp3_, _tmp6_);
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_g_free0 (_tmp6_);
#line 22 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_g_free0 (_tmp3_);
#line 23 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	result = FALSE;
#line 23 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	return result;
#line 163 "TagsWrapping.c"
}


static gboolean ____lambda12__gregex_eval_callback (GMatchInfo* match_info, GString* _result_, gpointer self) {
	gboolean result;
	result = ___lambda12_ (match_info, _result_);
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	return result;
#line 172 "TagsWrapping.c"
}


gchar* wrapInTags (const gchar* original) {
	gchar* result = NULL;
	gchar* res = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GError * _inner_error_ = NULL;
#line 1 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	g_return_val_if_fail (original != NULL, NULL);
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp0_ = original;
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	_tmp1_ = g_markup_escape_text (_tmp0_, (gssize) (-1));
#line 3 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	res = _tmp1_;
#line 190 "TagsWrapping.c"
	{
		GRegex* hashtagRegex = NULL;
		GRegex* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		GRegex* usernameRegex = NULL;
		GRegex* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		GRegex* _tmp10_ = NULL;
		const gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		GRegex* urlRegex = NULL;
		GRegex* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		GRegex* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
#line 6 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp2_ = g_regex_new ("#([\\p{L}0-9_]+)", 0, 0, &_inner_error_);
#line 6 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		hashtagRegex = _tmp2_;
#line 6 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 219 "TagsWrapping.c"
			goto __catch25_g_error;
		}
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp4_ = hashtagRegex;
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp5_ = res;
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp6_ = g_regex_replace_eval (_tmp4_, _tmp5_, (gssize) (-1), 0, 0, ____lambda10__gregex_eval_callback, NULL, &_inner_error_);
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp3_ = _tmp6_;
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_regex_unref0 (hashtagRegex);
#line 234 "TagsWrapping.c"
			goto __catch25_g_error;
		}
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp7_ = _tmp3_;
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp3_ = NULL;
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_free0 (res);
#line 7 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		res = _tmp7_;
#line 12 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp8_ = g_regex_new ("(@[a-zA-Z0-9_\\.]+)", 0, 0, &_inner_error_);
#line 12 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		usernameRegex = _tmp8_;
#line 12 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 12 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_free0 (_tmp3_);
#line 12 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_regex_unref0 (hashtagRegex);
#line 255 "TagsWrapping.c"
			goto __catch25_g_error;
		}
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp10_ = usernameRegex;
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp11_ = res;
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp12_ = g_regex_replace_eval (_tmp10_, _tmp11_, (gssize) (-1), 0, 0, ____lambda11__gregex_eval_callback, NULL, &_inner_error_);
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp9_ = _tmp12_;
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_regex_unref0 (usernameRegex);
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_free0 (_tmp3_);
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_regex_unref0 (hashtagRegex);
#line 274 "TagsWrapping.c"
			goto __catch25_g_error;
		}
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp13_ = _tmp9_;
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp9_ = NULL;
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_free0 (res);
#line 13 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		res = _tmp13_;
#line 20 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp14_ = g_regex_new ("([@#]![a-zA-Z0-9_-]+\\.)+([a-zA-Z]{2,6})(/[a-zA-Z0-9_-]+)*/?", 0, 0, &_inner_error_);
#line 20 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		urlRegex = _tmp14_;
#line 20 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 20 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_free0 (_tmp9_);
#line 20 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_regex_unref0 (usernameRegex);
#line 20 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_free0 (_tmp3_);
#line 20 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_regex_unref0 (hashtagRegex);
#line 299 "TagsWrapping.c"
			goto __catch25_g_error;
		}
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp16_ = urlRegex;
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp17_ = res;
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp18_ = g_regex_replace_eval (_tmp16_, _tmp17_, (gssize) (-1), 0, 0, ____lambda12__gregex_eval_callback, NULL, &_inner_error_);
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp15_ = _tmp18_;
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_regex_unref0 (urlRegex);
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_free0 (_tmp9_);
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_regex_unref0 (usernameRegex);
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_free0 (_tmp3_);
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
			_g_regex_unref0 (hashtagRegex);
#line 322 "TagsWrapping.c"
			goto __catch25_g_error;
		}
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp19_ = _tmp15_;
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp15_ = NULL;
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_free0 (res);
#line 21 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		res = _tmp19_;
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_free0 (_tmp15_);
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_regex_unref0 (urlRegex);
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_free0 (_tmp9_);
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_regex_unref0 (usernameRegex);
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_free0 (_tmp3_);
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_regex_unref0 (hashtagRegex);
#line 345 "TagsWrapping.c"
	}
	goto __finally25;
	__catch25_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_ = NULL;
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		e = _inner_error_;
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_inner_error_ = NULL;
#line 28 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp20_ = e->message;
#line 28 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp21_ = g_strconcat ("Something wrong with regexes: ", _tmp20_, NULL);
#line 28 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp22_ = _tmp21_;
#line 28 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp23_ = g_strconcat (_tmp22_, ".\n", NULL);
#line 28 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_tmp24_ = _tmp23_;
#line 28 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		g_error ("TagsWrapping.vala:28: %s", _tmp24_);
#line 28 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_free0 (_tmp24_);
#line 28 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_free0 (_tmp22_);
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_error_free0 (e);
#line 378 "TagsWrapping.c"
	}
	__finally25:
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		_g_free0 (res);
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		g_clear_error (&_inner_error_);
#line 4 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
		return NULL;
#line 391 "TagsWrapping.c"
	}
#line 30 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	result = res;
#line 30 "/all/Documents/Programming/vala/photostream/src/Utils/TagsWrapping.vala"
	return result;
#line 397 "TagsWrapping.c"
}



