/* main.c generated by valac 0.26.1.9-22126, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gst/gst.h>
#include <libxml/parser.h>
#include <libnotify/notify.h>
#include <granite.h>


#define PHOTO_STREAM_TYPE_APP (photo_stream_app_get_type ())
#define PHOTO_STREAM_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_TYPE_APP, PhotoStreamApp))
#define PHOTO_STREAM_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_TYPE_APP, PhotoStreamAppClass))
#define PHOTO_STREAM_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_TYPE_APP))
#define PHOTO_STREAM_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_TYPE_APP))
#define PHOTO_STREAM_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_TYPE_APP, PhotoStreamAppClass))

typedef struct _PhotoStreamApp PhotoStreamApp;
typedef struct _PhotoStreamAppClass PhotoStreamAppClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



gint _vala_main (gchar** args, int args_length1);
GType photo_stream_app_get_type (void) G_GNUC_CONST;
PhotoStreamApp* photo_stream_app_new (void);
PhotoStreamApp* photo_stream_app_construct (GType object_type);


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	PhotoStreamApp* app = NULL;
	PhotoStreamApp* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
#line 2 "/all/Documents/Programming/vala/photostream/src/main.vala"
	gtk_init (&args_length1, &args);
#line 3 "/all/Documents/Programming/vala/photostream/src/main.vala"
	gst_init (&args_length1, &args);
#line 4 "/all/Documents/Programming/vala/photostream/src/main.vala"
	xmlInitParser ();
#line 5 "/all/Documents/Programming/vala/photostream/src/main.vala"
	notify_init ("PhotoStream");
#line 6 "/all/Documents/Programming/vala/photostream/src/main.vala"
	_tmp0_ = photo_stream_app_new ();
#line 6 "/all/Documents/Programming/vala/photostream/src/main.vala"
	app = _tmp0_;
#line 8 "/all/Documents/Programming/vala/photostream/src/main.vala"
	_tmp1_ = args;
#line 8 "/all/Documents/Programming/vala/photostream/src/main.vala"
	_tmp1__length1 = args_length1;
#line 8 "/all/Documents/Programming/vala/photostream/src/main.vala"
	_tmp2_ = granite_application_run ((GraniteApplication*) app, _tmp1_, _tmp1__length1);
#line 8 "/all/Documents/Programming/vala/photostream/src/main.vala"
	result = _tmp2_;
#line 8 "/all/Documents/Programming/vala/photostream/src/main.vala"
	_g_object_unref0 (app);
#line 8 "/all/Documents/Programming/vala/photostream/src/main.vala"
	return result;
#line 67 "main.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,32,0)
	g_thread_init (NULL);
#endif
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 1 "/all/Documents/Programming/vala/photostream/src/main.vala"
	return _vala_main (argv, argc);
#line 80 "main.c"
}



