/* CommentsBox.c generated by valac 0.26.1.9-22126, the Vala compiler
 * generated from CommentsBox.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>
#include <gdk/gdk.h>
#include <gio/gio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>


#define PHOTO_STREAM_WIDGETS_TYPE_COMMENT_BOX (photo_stream_widgets_comment_box_get_type ())
#define PHOTO_STREAM_WIDGETS_COMMENT_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_WIDGETS_TYPE_COMMENT_BOX, PhotoStreamWidgetsCommentBox))
#define PHOTO_STREAM_WIDGETS_COMMENT_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_WIDGETS_TYPE_COMMENT_BOX, PhotoStreamWidgetsCommentBoxClass))
#define PHOTO_STREAM_WIDGETS_IS_COMMENT_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_WIDGETS_TYPE_COMMENT_BOX))
#define PHOTO_STREAM_WIDGETS_IS_COMMENT_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_WIDGETS_TYPE_COMMENT_BOX))
#define PHOTO_STREAM_WIDGETS_COMMENT_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_WIDGETS_TYPE_COMMENT_BOX, PhotoStreamWidgetsCommentBoxClass))

typedef struct _PhotoStreamWidgetsCommentBox PhotoStreamWidgetsCommentBox;
typedef struct _PhotoStreamWidgetsCommentBoxClass PhotoStreamWidgetsCommentBoxClass;
typedef struct _PhotoStreamWidgetsCommentBoxPrivate PhotoStreamWidgetsCommentBoxPrivate;

#define PHOTO_STREAM_UTILS_TYPE_COMMENT (photo_stream_utils_comment_get_type ())
#define PHOTO_STREAM_UTILS_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_COMMENT, PhotoStreamUtilsComment))
#define PHOTO_STREAM_UTILS_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_COMMENT, PhotoStreamUtilsCommentClass))
#define PHOTO_STREAM_UTILS_IS_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_COMMENT))
#define PHOTO_STREAM_UTILS_IS_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_COMMENT))
#define PHOTO_STREAM_UTILS_COMMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_COMMENT, PhotoStreamUtilsCommentClass))

typedef struct _PhotoStreamUtilsComment PhotoStreamUtilsComment;
typedef struct _PhotoStreamUtilsCommentClass PhotoStreamUtilsCommentClass;
#define _photo_stream_utils_comment_unref0(var) ((var == NULL) ? NULL : (var = (photo_stream_utils_comment_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _PhotoStreamUtilsCommentPrivate PhotoStreamUtilsCommentPrivate;

#define PHOTO_STREAM_UTILS_TYPE_USER (photo_stream_utils_user_get_type ())
#define PHOTO_STREAM_UTILS_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_USER, PhotoStreamUtilsUser))
#define PHOTO_STREAM_UTILS_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_USER, PhotoStreamUtilsUserClass))
#define PHOTO_STREAM_UTILS_IS_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_USER))
#define PHOTO_STREAM_UTILS_IS_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_USER))
#define PHOTO_STREAM_UTILS_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_USER, PhotoStreamUtilsUserClass))

typedef struct _PhotoStreamUtilsUser PhotoStreamUtilsUser;
typedef struct _PhotoStreamUtilsUserClass PhotoStreamUtilsUserClass;
typedef struct _PhotoStreamUtilsUserPrivate PhotoStreamUtilsUserPrivate;

#define PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP (photo_stream_utils_relationship_get_type ())
#define PHOTO_STREAM_UTILS_RELATIONSHIP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP, PhotoStreamUtilsRelationship))
#define PHOTO_STREAM_UTILS_RELATIONSHIP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP, PhotoStreamUtilsRelationshipClass))
#define PHOTO_STREAM_UTILS_IS_RELATIONSHIP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP))
#define PHOTO_STREAM_UTILS_IS_RELATIONSHIP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP))
#define PHOTO_STREAM_UTILS_RELATIONSHIP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_RELATIONSHIP, PhotoStreamUtilsRelationshipClass))

typedef struct _PhotoStreamUtilsRelationship PhotoStreamUtilsRelationship;
typedef struct _PhotoStreamUtilsRelationshipClass PhotoStreamUtilsRelationshipClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _PhotoStreamWidgetsCommentBox {
	GtkBox parent_instance;
	PhotoStreamWidgetsCommentBoxPrivate * priv;
	PhotoStreamUtilsComment* comment;
	GtkAlignment* avatarAlignment;
	GtkAlignment* textAlignment;
	GtkBox* textBox;
	GtkLabel* textLabel;
	GtkEventBox* avatarBox;
	GtkEventBox* textEventBox;
	GtkImage* avatar;
	GtkToolButton* removeCommentButton;
	gint AVATAR_SIZE;
};

struct _PhotoStreamWidgetsCommentBoxClass {
	GtkBoxClass parent_class;
};

struct _PhotoStreamUtilsComment {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsCommentPrivate * priv;
	GDateTime* creationTime;
	gchar* text;
	PhotoStreamUtilsUser* user;
	gchar* id;
};

struct _PhotoStreamUtilsCommentClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsComment *self);
};

struct _PhotoStreamUtilsUser {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsUserPrivate * priv;
	gchar* username;
	gchar* profilePicture;
	gchar* fullName;
	gchar* id;
	gchar* website;
	gchar* bio;
	gint64 mediaCount;
	gint64 followers;
	gint64 followed;
	PhotoStreamUtilsRelationship* relationship;
};

struct _PhotoStreamUtilsUserClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsUser *self);
};


static gpointer photo_stream_widgets_comment_box_parent_class = NULL;
extern gchar* photo_stream_app_CACHE_AVATARS;
extern PhotoStreamUtilsUser* photo_stream_app_selfUser;

GType photo_stream_widgets_comment_box_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_comment_ref (gpointer instance);
void photo_stream_utils_comment_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_comment (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_comment (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_comment (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_comment (const GValue* value);
GType photo_stream_utils_comment_get_type (void) G_GNUC_CONST;
enum  {
	PHOTO_STREAM_WIDGETS_COMMENT_BOX_DUMMY_PROPERTY
};
PhotoStreamWidgetsCommentBox* photo_stream_widgets_comment_box_new (PhotoStreamUtilsComment* comment, gboolean withAvatar);
PhotoStreamWidgetsCommentBox* photo_stream_widgets_comment_box_construct (GType object_type, PhotoStreamUtilsComment* comment, gboolean withAvatar);
gchar* wrapInTags (const gchar* original);
gpointer photo_stream_utils_user_ref (gpointer instance);
void photo_stream_utils_user_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_user (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_user (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_user (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_user (const GValue* value);
GType photo_stream_utils_user_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_relationship_ref (gpointer instance);
void photo_stream_utils_relationship_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_relationship (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_relationship (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_relationship (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_relationship (const GValue* value);
GType photo_stream_utils_relationship_get_type (void) G_GNUC_CONST;
gchar* getFileName (const gchar* url);
void downloadFile (const gchar* url, const gchar* filename, GError** error);
static gboolean ____lambda13_ (PhotoStreamWidgetsCommentBox* self, GdkEventCrossing* event);
static gboolean _____lambda13__gtk_widget_enter_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self);
static void photo_stream_widgets_comment_box_finalize (GObject* obj);


static gpointer _photo_stream_utils_comment_ref0 (gpointer self) {
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	return self ? photo_stream_utils_comment_ref (self) : NULL;
#line 164 "CommentsBox.c"
}


static gboolean ____lambda13_ (PhotoStreamWidgetsCommentBox* self, GdkEventCrossing* event) {
	gboolean result = FALSE;
	GdkEventCrossing* _tmp0_ = NULL;
	GdkWindow* _tmp1_ = NULL;
	GdkDisplay* _tmp2_ = NULL;
	GdkCursor* _tmp3_ = NULL;
	GdkCursor* _tmp4_ = NULL;
#line 88 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp0_ = event;
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp1_ = _tmp0_->window;
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp2_ = gdk_display_get_default ();
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp3_ = gdk_cursor_new_from_name (_tmp2_, "hand2");
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp4_ = _tmp3_;
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gdk_window_set_cursor (_tmp1_, _tmp4_);
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (_tmp4_);
#line 92 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	result = FALSE;
#line 92 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	return result;
#line 195 "CommentsBox.c"
}


static gboolean _____lambda13__gtk_widget_enter_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self) {
	gboolean result;
	result = ____lambda13_ ((PhotoStreamWidgetsCommentBox*) self, event);
#line 88 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	return result;
#line 204 "CommentsBox.c"
}


PhotoStreamWidgetsCommentBox* photo_stream_widgets_comment_box_construct (GType object_type, PhotoStreamUtilsComment* comment, gboolean withAvatar) {
	PhotoStreamWidgetsCommentBox * self = NULL;
	PhotoStreamUtilsComment* _tmp0_ = NULL;
	PhotoStreamUtilsComment* _tmp1_ = NULL;
	GtkAlignment* _tmp2_ = NULL;
	GtkAlignment* _tmp3_ = NULL;
	GtkAlignment* _tmp4_ = NULL;
	GtkAlignment* _tmp5_ = NULL;
	GtkAlignment* _tmp6_ = NULL;
	GtkAlignment* _tmp7_ = NULL;
	GtkAlignment* _tmp8_ = NULL;
	GtkAlignment* _tmp9_ = NULL;
	GtkAlignment* _tmp10_ = NULL;
	GtkAlignment* _tmp11_ = NULL;
	GtkBox* _tmp12_ = NULL;
	GtkEventBox* _tmp13_ = NULL;
	GtkLabel* _tmp14_ = NULL;
	GtkLabel* _tmp15_ = NULL;
	PhotoStreamUtilsComment* _tmp16_ = NULL;
	PhotoStreamUtilsUser* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	PhotoStreamUtilsComment* _tmp27_ = NULL;
	const gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	GtkLabel* _tmp33_ = NULL;
	GtkLabel* _tmp34_ = NULL;
	GtkLabel* _tmp35_ = NULL;
	GtkLabel* _tmp36_ = NULL;
	GtkLabel* _tmp37_ = NULL;
	GtkLabel* _tmp38_ = NULL;
	GtkEventBox* _tmp39_ = NULL;
	gboolean _tmp40_ = FALSE;
	GtkImage* _tmp79_ = NULL;
	GtkImage* _tmp80_ = NULL;
	GtkToolButton* _tmp81_ = NULL;
	GtkBox* _tmp82_ = NULL;
	GtkLabel* _tmp83_ = NULL;
	GtkEventBox* _tmp84_ = NULL;
	GtkBox* _tmp85_ = NULL;
	GtkAlignment* _tmp86_ = NULL;
	GtkEventBox* _tmp87_ = NULL;
	GtkAlignment* _tmp88_ = NULL;
	PhotoStreamUtilsUser* _tmp89_ = NULL;
	const gchar* _tmp90_ = NULL;
	PhotoStreamUtilsComment* _tmp91_ = NULL;
	PhotoStreamUtilsUser* _tmp92_ = NULL;
	const gchar* _tmp93_ = NULL;
	GError * _inner_error_ = NULL;
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_return_val_if_fail (comment != NULL, NULL);
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	self = (PhotoStreamWidgetsCommentBox*) g_object_new (object_type, NULL);
#line 21 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_widget_set_halign ((GtkWidget*) self, GTK_ALIGN_START);
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp0_ = comment;
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp1_ = _photo_stream_utils_comment_ref0 (_tmp0_);
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_photo_stream_utils_comment_unref0 (self->comment);
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	self->comment = _tmp1_;
#line 25 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp2_ = (GtkAlignment*) gtk_alignment_new ((gfloat) 0, 0.5f, (gfloat) 1, (gfloat) 0);
#line 25 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_ref_sink (_tmp2_);
#line 25 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->textAlignment);
#line 25 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	self->textAlignment = _tmp2_;
#line 26 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp3_ = self->textAlignment;
#line 26 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_set (_tmp3_, "top-padding", (guint) 1, NULL);
#line 27 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp4_ = self->textAlignment;
#line 27 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_set (_tmp4_, "right-padding", (guint) 0, NULL);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp5_ = self->textAlignment;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_set (_tmp5_, "bottom-padding", (guint) 1, NULL);
#line 29 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp6_ = self->textAlignment;
#line 29 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_set (_tmp6_, "left-padding", (guint) 0, NULL);
#line 31 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp7_ = (GtkAlignment*) gtk_alignment_new ((gfloat) 0, (gfloat) 1, (gfloat) 1, (gfloat) 1);
#line 31 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_ref_sink (_tmp7_);
#line 31 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->avatarAlignment);
#line 31 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	self->avatarAlignment = _tmp7_;
#line 32 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp8_ = self->avatarAlignment;
#line 32 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_set (_tmp8_, "top-padding", (guint) 1, NULL);
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp9_ = self->avatarAlignment;
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_set (_tmp9_, "right-padding", (guint) 6, NULL);
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp10_ = self->avatarAlignment;
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_set (_tmp10_, "bottom-padding", (guint) 1, NULL);
#line 35 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp11_ = self->avatarAlignment;
#line 35 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_set (_tmp11_, "left-padding", (guint) 0, NULL);
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp12_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_ref_sink (_tmp12_);
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->textBox);
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	self->textBox = _tmp12_;
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp13_ = (GtkEventBox*) gtk_event_box_new ();
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_ref_sink (_tmp13_);
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->textEventBox);
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	self->textEventBox = _tmp13_;
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp14_ = (GtkLabel*) gtk_label_new ("");
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_ref_sink (_tmp14_);
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->textLabel);
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	self->textLabel = _tmp14_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp15_ = self->textLabel;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp16_ = comment;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp17_ = _tmp16_->user;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp18_ = _tmp17_->username;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp19_ = g_strconcat ("@", _tmp18_, NULL);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp20_ = _tmp19_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp21_ = wrapInTags (_tmp20_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp22_ = _tmp21_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp23_ = g_strconcat ("<b>", _tmp22_, NULL);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp24_ = _tmp23_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp25_ = g_strconcat (_tmp24_, "</b> ", NULL);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp26_ = _tmp25_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp27_ = comment;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp28_ = _tmp27_->text;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp29_ = wrapInTags (_tmp28_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp30_ = _tmp29_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp31_ = g_strconcat (_tmp26_, _tmp30_, NULL);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp32_ = _tmp31_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_label_set_markup (_tmp15_, _tmp32_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_free0 (_tmp32_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_free0 (_tmp30_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_free0 (_tmp26_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_free0 (_tmp24_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_free0 (_tmp22_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_free0 (_tmp20_);
#line 41 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp33_ = self->textLabel;
#line 41 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_label_set_line_wrap (_tmp33_, TRUE);
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp34_ = self->textLabel;
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_label_set_line_wrap_mode (_tmp34_, PANGO_WRAP_WORD_CHAR);
#line 44 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp35_ = self->textLabel;
#line 44 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_label_set_justify (_tmp35_, GTK_JUSTIFY_LEFT);
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp36_ = self->textLabel;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp36_, GTK_ALIGN_START);
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp37_ = self->textLabel;
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp37_, GTK_ALIGN_START);
#line 47 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp38_ = self->textLabel;
#line 47 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_set ((GtkMisc*) _tmp38_, "xalign", (gfloat) 0, NULL);
#line 49 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_widget_set_events ((GtkWidget*) self, (gint) GDK_BUTTON_RELEASE_MASK);
#line 50 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp39_ = self->textEventBox;
#line 50 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_widget_set_events ((GtkWidget*) _tmp39_, (gint) GDK_BUTTON_RELEASE_MASK);
#line 52 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp40_ = withAvatar;
#line 52 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	if (_tmp40_) {
#line 437 "CommentsBox.c"
		gboolean isImageLoaded = FALSE;
		gchar* avatarFileName = NULL;
		const gchar* _tmp41_ = NULL;
		PhotoStreamUtilsComment* _tmp42_ = NULL;
		PhotoStreamUtilsUser* _tmp43_ = NULL;
		const gchar* _tmp44_ = NULL;
		gchar* _tmp45_ = NULL;
		gchar* _tmp46_ = NULL;
		gchar* _tmp47_ = NULL;
		gchar* _tmp48_ = NULL;
		GFile* file = NULL;
		const gchar* _tmp49_ = NULL;
		GFile* _tmp50_ = NULL;
		GFile* _tmp51_ = NULL;
		gboolean _tmp52_ = FALSE;
		gboolean _tmp57_ = FALSE;
#line 54 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		isImageLoaded = TRUE;
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp41_ = photo_stream_app_CACHE_AVATARS;
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp42_ = comment;
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp43_ = _tmp42_->user;
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp44_ = _tmp43_->profilePicture;
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp45_ = getFileName (_tmp44_);
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp46_ = _tmp45_;
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp47_ = g_strconcat (_tmp41_, _tmp46_, NULL);
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp48_ = _tmp47_;
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_g_free0 (_tmp46_);
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		avatarFileName = _tmp48_;
#line 56 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp49_ = avatarFileName;
#line 56 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp50_ = g_file_new_for_path (_tmp49_);
#line 56 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		file = _tmp50_;
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp51_ = file;
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp52_ = g_file_query_exists (_tmp51_, NULL);
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		if (!_tmp52_) {
#line 488 "CommentsBox.c"
			{
				PhotoStreamUtilsComment* _tmp53_ = NULL;
				PhotoStreamUtilsUser* _tmp54_ = NULL;
				const gchar* _tmp55_ = NULL;
				const gchar* _tmp56_ = NULL;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_tmp53_ = comment;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_tmp54_ = _tmp53_->user;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_tmp55_ = _tmp54_->profilePicture;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_tmp56_ = avatarFileName;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				downloadFile (_tmp55_, _tmp56_, &_inner_error_);
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 506 "CommentsBox.c"
					goto __catch45_g_error;
				}
			}
			goto __finally45;
			__catch45_g_error:
			{
				GError* e = NULL;
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				e = _inner_error_;
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_inner_error_ = NULL;
#line 63 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				isImageLoaded = FALSE;
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_g_error_free0 (e);
#line 522 "CommentsBox.c"
			}
			__finally45:
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_g_object_unref0 (file);
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_g_free0 (avatarFileName);
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				g_clear_error (&_inner_error_);
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				return NULL;
#line 537 "CommentsBox.c"
			}
		}
#line 66 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp57_ = isImageLoaded;
#line 66 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		if (_tmp57_) {
#line 544 "CommentsBox.c"
			GtkImage* _tmp58_ = NULL;
			GtkImage* _tmp59_ = NULL;
			gint _tmp60_ = 0;
			gint _tmp61_ = 0;
			GtkEventBox* _tmp62_ = NULL;
			GtkEventBox* _tmp63_ = NULL;
			GtkImage* _tmp64_ = NULL;
			GdkPixbuf* avatarPixbuf = NULL;
			GdkPixbuf* _tmp69_ = NULL;
			gint _tmp70_ = 0;
			gint _tmp71_ = 0;
			GdkPixbuf* _tmp72_ = NULL;
			GtkImage* _tmp73_ = NULL;
			GdkPixbuf* _tmp74_ = NULL;
			GtkAlignment* _tmp75_ = NULL;
			GtkEventBox* _tmp76_ = NULL;
			GtkAlignment* _tmp77_ = NULL;
			GtkEventBox* _tmp78_ = NULL;
#line 68 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp58_ = (GtkImage*) gtk_image_new ();
#line 68 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			g_object_ref_sink (_tmp58_);
#line 68 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_g_object_unref0 (self->avatar);
#line 68 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			self->avatar = _tmp58_;
#line 69 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp59_ = self->avatar;
#line 69 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp60_ = self->AVATAR_SIZE;
#line 69 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp61_ = self->AVATAR_SIZE;
#line 69 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			gtk_widget_set_size_request ((GtkWidget*) _tmp59_, _tmp60_, _tmp61_);
#line 70 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp62_ = (GtkEventBox*) gtk_event_box_new ();
#line 70 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			g_object_ref_sink (_tmp62_);
#line 70 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_g_object_unref0 (self->avatarBox);
#line 70 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			self->avatarBox = _tmp62_;
#line 71 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp63_ = self->avatarBox;
#line 71 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp64_ = self->avatar;
#line 71 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			gtk_container_add ((GtkContainer*) _tmp63_, (GtkWidget*) _tmp64_);
#line 593 "CommentsBox.c"
			{
				GdkPixbuf* _tmp65_ = NULL;
				const gchar* _tmp66_ = NULL;
				GdkPixbuf* _tmp67_ = NULL;
				GdkPixbuf* _tmp68_ = NULL;
#line 75 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_tmp66_ = avatarFileName;
#line 75 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_tmp67_ = gdk_pixbuf_new_from_file (_tmp66_, &_inner_error_);
#line 75 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_tmp65_ = _tmp67_;
#line 75 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 607 "CommentsBox.c"
					goto __catch46_g_error;
				}
#line 75 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_tmp68_ = _tmp65_;
#line 75 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_tmp65_ = NULL;
#line 75 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_g_object_unref0 (avatarPixbuf);
#line 75 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				avatarPixbuf = _tmp68_;
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_g_object_unref0 (_tmp65_);
#line 620 "CommentsBox.c"
			}
			goto __finally46;
			__catch46_g_error:
			{
				GError* e = NULL;
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				e = _inner_error_;
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_inner_error_ = NULL;
#line 79 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				g_error ("CommentsBox.vala:79: Something wrong with file loading.\n");
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_g_error_free0 (e);
#line 634 "CommentsBox.c"
			}
			__finally46:
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_g_object_unref0 (avatarPixbuf);
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_g_object_unref0 (file);
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				_g_free0 (avatarFileName);
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				g_clear_error (&_inner_error_);
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
				return NULL;
#line 651 "CommentsBox.c"
			}
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp69_ = avatarPixbuf;
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp70_ = self->AVATAR_SIZE;
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp71_ = self->AVATAR_SIZE;
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp72_ = gdk_pixbuf_scale_simple (_tmp69_, _tmp70_, _tmp71_, GDK_INTERP_BILINEAR);
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_g_object_unref0 (avatarPixbuf);
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			avatarPixbuf = _tmp72_;
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp73_ = self->avatar;
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp74_ = avatarPixbuf;
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			gtk_image_set_from_pixbuf (_tmp73_, _tmp74_);
#line 85 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp75_ = self->avatarAlignment;
#line 85 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp76_ = self->avatarBox;
#line 85 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			gtk_container_add ((GtkContainer*) _tmp75_, (GtkWidget*) _tmp76_);
#line 86 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp77_ = self->avatarAlignment;
#line 86 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp77_, FALSE, TRUE, (guint) 0);
#line 88 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_tmp78_ = self->avatarBox;
#line 88 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			g_signal_connect_object ((GtkWidget*) _tmp78_, "enter-notify-event", (GCallback) _____lambda13__gtk_widget_enter_notify_event, self, 0);
#line 66 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
			_g_object_unref0 (avatarPixbuf);
#line 687 "CommentsBox.c"
		}
#line 52 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_g_object_unref0 (file);
#line 52 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_g_free0 (avatarFileName);
#line 693 "CommentsBox.c"
	}
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp79_ = (GtkImage*) gtk_image_new_from_icon_name ("dialog-cancel", GTK_ICON_SIZE_LARGE_TOOLBAR);
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_ref_sink (_tmp79_);
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp80_ = _tmp79_;
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp81_ = (GtkToolButton*) gtk_tool_button_new ((GtkWidget*) _tmp80_, "Go back");
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	g_object_ref_sink (_tmp81_);
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->removeCommentButton);
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	self->removeCommentButton = _tmp81_;
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (_tmp80_);
#line 100 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp82_ = self->textBox;
#line 100 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp83_ = self->textLabel;
#line 100 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_container_add ((GtkContainer*) _tmp82_, (GtkWidget*) _tmp83_);
#line 101 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp84_ = self->textEventBox;
#line 101 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp85_ = self->textBox;
#line 101 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_container_add ((GtkContainer*) _tmp84_, (GtkWidget*) _tmp85_);
#line 102 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp86_ = self->textAlignment;
#line 102 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp87_ = self->textEventBox;
#line 102 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_container_add ((GtkContainer*) _tmp86_, (GtkWidget*) _tmp87_);
#line 103 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp88_ = self->textAlignment;
#line 103 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp88_);
#line 104 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp89_ = photo_stream_app_selfUser;
#line 104 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp90_ = _tmp89_->id;
#line 104 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp91_ = comment;
#line 104 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp92_ = _tmp91_->user;
#line 104 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_tmp93_ = _tmp92_->id;
#line 104 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	if (g_strcmp0 (_tmp90_, _tmp93_) == 0) {
#line 745 "CommentsBox.c"
		GtkToolButton* _tmp94_ = NULL;
#line 105 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		_tmp94_ = self->removeCommentButton;
#line 105 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
		gtk_box_pack_end ((GtkBox*) self, (GtkWidget*) _tmp94_, FALSE, TRUE, (guint) 0);
#line 751 "CommentsBox.c"
	}
#line 106 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, 625, -1);
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	return self;
#line 759 "CommentsBox.c"
}


PhotoStreamWidgetsCommentBox* photo_stream_widgets_comment_box_new (PhotoStreamUtilsComment* comment, gboolean withAvatar) {
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	return photo_stream_widgets_comment_box_construct (PHOTO_STREAM_WIDGETS_TYPE_COMMENT_BOX, comment, withAvatar);
#line 766 "CommentsBox.c"
}


static void photo_stream_widgets_comment_box_class_init (PhotoStreamWidgetsCommentBoxClass * klass) {
#line 4 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	photo_stream_widgets_comment_box_parent_class = g_type_class_peek_parent (klass);
#line 4 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	G_OBJECT_CLASS (klass)->finalize = photo_stream_widgets_comment_box_finalize;
#line 775 "CommentsBox.c"
}


static void photo_stream_widgets_comment_box_instance_init (PhotoStreamWidgetsCommentBox * self) {
#line 17 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	self->AVATAR_SIZE = 35;
#line 782 "CommentsBox.c"
}


static void photo_stream_widgets_comment_box_finalize (GObject* obj) {
	PhotoStreamWidgetsCommentBox * self;
#line 4 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PHOTO_STREAM_WIDGETS_TYPE_COMMENT_BOX, PhotoStreamWidgetsCommentBox);
#line 6 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_photo_stream_utils_comment_unref0 (self->comment);
#line 8 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->avatarAlignment);
#line 9 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->textAlignment);
#line 11 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->textBox);
#line 12 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->textLabel);
#line 13 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->avatarBox);
#line 14 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->textEventBox);
#line 15 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->avatar);
#line 16 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	_g_object_unref0 (self->removeCommentButton);
#line 4 "/all/Documents/Programming/vala/photostream/src/Widgets/CommentsBox.vala"
	G_OBJECT_CLASS (photo_stream_widgets_comment_box_parent_class)->finalize (obj);
#line 810 "CommentsBox.c"
}


GType photo_stream_widgets_comment_box_get_type (void) {
	static volatile gsize photo_stream_widgets_comment_box_type_id__volatile = 0;
	if (g_once_init_enter (&photo_stream_widgets_comment_box_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PhotoStreamWidgetsCommentBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) photo_stream_widgets_comment_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PhotoStreamWidgetsCommentBox), 0, (GInstanceInitFunc) photo_stream_widgets_comment_box_instance_init, NULL };
		GType photo_stream_widgets_comment_box_type_id;
		photo_stream_widgets_comment_box_type_id = g_type_register_static (gtk_box_get_type (), "PhotoStreamWidgetsCommentBox", &g_define_type_info, 0);
		g_once_init_leave (&photo_stream_widgets_comment_box_type_id__volatile, photo_stream_widgets_comment_box_type_id);
	}
	return photo_stream_widgets_comment_box_type_id__volatile;
}



