/* DateLabel.c generated by valac 0.26.1.9-22126, the Vala compiler
 * generated from DateLabel.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL (photo_stream_widgets_date_label_get_type ())
#define PHOTO_STREAM_WIDGETS_DATE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, PhotoStreamWidgetsDateLabel))
#define PHOTO_STREAM_WIDGETS_DATE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, PhotoStreamWidgetsDateLabelClass))
#define PHOTO_STREAM_WIDGETS_IS_DATE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL))
#define PHOTO_STREAM_WIDGETS_IS_DATE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL))
#define PHOTO_STREAM_WIDGETS_DATE_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, PhotoStreamWidgetsDateLabelClass))

typedef struct _PhotoStreamWidgetsDateLabel PhotoStreamWidgetsDateLabel;
typedef struct _PhotoStreamWidgetsDateLabelClass PhotoStreamWidgetsDateLabelClass;
typedef struct _PhotoStreamWidgetsDateLabelPrivate PhotoStreamWidgetsDateLabelPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _PhotoStreamWidgetsDateLabel {
	GtkEventBox parent_instance;
	PhotoStreamWidgetsDateLabelPrivate * priv;
	GtkLabel* dateLabel;
	GDateTime* time;
};

struct _PhotoStreamWidgetsDateLabelClass {
	GtkEventBoxClass parent_class;
};


static gpointer photo_stream_widgets_date_label_parent_class = NULL;

GType photo_stream_widgets_date_label_get_type (void) G_GNUC_CONST;
enum  {
	PHOTO_STREAM_WIDGETS_DATE_LABEL_DUMMY_PROPERTY
};
#define PHOTO_STREAM_WIDGETS_DATE_LABEL_TIME_REFRESH_INTERVAL 10
PhotoStreamWidgetsDateLabel* photo_stream_widgets_date_label_new (GDateTime* time);
PhotoStreamWidgetsDateLabel* photo_stream_widgets_date_label_construct (GType object_type, GDateTime* time);
static void photo_stream_widgets_date_label_updateTime (PhotoStreamWidgetsDateLabel* self);
static gboolean __lambda9_ (PhotoStreamWidgetsDateLabel* self);
static gboolean ___lambda9__gsource_func (gpointer self);
static void photo_stream_widgets_date_label_finalize (GObject* obj);


static gpointer _g_date_time_ref0 (gpointer self) {
#line 11 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	return self ? g_date_time_ref (self) : NULL;
#line 57 "DateLabel.c"
}


PhotoStreamWidgetsDateLabel* photo_stream_widgets_date_label_construct (GType object_type, GDateTime* time) {
	PhotoStreamWidgetsDateLabel * self = NULL;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
#line 9 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	g_return_val_if_fail (time != NULL, NULL);
#line 9 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	self = (PhotoStreamWidgetsDateLabel*) g_object_new (object_type, NULL);
#line 11 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp0_ = time;
#line 11 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp1_ = _g_date_time_ref0 (_tmp0_);
#line 11 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_g_date_time_unref0 (self->time);
#line 11 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	self->time = _tmp1_;
#line 12 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp2_ = (GtkLabel*) gtk_label_new ("");
#line 12 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	g_object_ref_sink (_tmp2_);
#line 12 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_g_object_unref0 (self->dateLabel);
#line 12 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	self->dateLabel = _tmp2_;
#line 13 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp3_ = self->dateLabel;
#line 13 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp3_, GTK_ALIGN_START);
#line 14 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp4_ = self->dateLabel;
#line 14 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp4_);
#line 16 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	photo_stream_widgets_date_label_updateTime (self);
#line 9 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	return self;
#line 100 "DateLabel.c"
}


PhotoStreamWidgetsDateLabel* photo_stream_widgets_date_label_new (GDateTime* time) {
#line 9 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	return photo_stream_widgets_date_label_construct (PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, time);
#line 107 "DateLabel.c"
}


static gboolean __lambda9_ (PhotoStreamWidgetsDateLabel* self) {
	gboolean result = FALSE;
#line 54 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	photo_stream_widgets_date_label_updateTime (self);
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	result = FALSE;
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	return result;
#line 119 "DateLabel.c"
}


static gboolean ___lambda9__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda9_ ((PhotoStreamWidgetsDateLabel*) self);
#line 53 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	return result;
#line 128 "DateLabel.c"
}


static void photo_stream_widgets_date_label_updateTime (PhotoStreamWidgetsDateLabel* self) {
	GDateTime* currentTime = NULL;
	GDateTime* _tmp0_ = NULL;
	gint64 timePassed = 0LL;
	GDateTime* _tmp1_ = NULL;
	gint64 _tmp2_ = 0LL;
	GDateTime* _tmp3_ = NULL;
	gint64 _tmp4_ = 0LL;
	const gchar* _tmp5_ = NULL;
	gint64 _tmp6_ = 0LL;
	gchar* time = NULL;
	gint64 _tmp7_ = 0LL;
	gchar* _tmp8_ = NULL;
	gint64 _tmp9_ = 0LL;
	gint64 _tmp15_ = 0LL;
	gint64 _tmp21_ = 0LL;
	gint64 _tmp27_ = 0LL;
	gint64 _tmp33_ = 0LL;
	GtkLabel* _tmp39_ = NULL;
	const gchar* _tmp40_ = NULL;
	gchar* _tmp41_ = NULL;
	gchar* _tmp42_ = NULL;
	gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	g_return_if_fail (self != NULL);
#line 21 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 21 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	currentTime = _tmp0_;
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp1_ = currentTime;
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp2_ = g_date_time_to_unix (_tmp1_);
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp3_ = self->time;
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp4_ = g_date_time_to_unix (_tmp3_);
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	timePassed = _tmp2_ - _tmp4_;
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp6_ = timePassed;
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	if (_tmp6_ == ((gint64) 1)) {
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp5_ = "";
#line 178 "DateLabel.c"
	} else {
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp5_ = "s";
#line 182 "DateLabel.c"
	}
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp7_ = timePassed;
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp8_ = g_strdup_printf ("%lld second%s ago.", _tmp7_, _tmp5_);
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	time = _tmp8_;
#line 25 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp9_ = timePassed;
#line 25 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	if (_tmp9_ >= ((gint64) 60)) {
#line 194 "DateLabel.c"
		gint64 _tmp10_ = 0LL;
		const gchar* _tmp11_ = NULL;
		gint64 _tmp12_ = 0LL;
		gint64 _tmp13_ = 0LL;
		gchar* _tmp14_ = NULL;
#line 27 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp10_ = timePassed;
#line 27 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		timePassed = _tmp10_ / 60;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp12_ = timePassed;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		if (_tmp12_ == ((gint64) 1)) {
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
			_tmp11_ = "";
#line 210 "DateLabel.c"
		} else {
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
			_tmp11_ = "s";
#line 214 "DateLabel.c"
		}
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp13_ = timePassed;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp14_ = g_strdup_printf ("%lld minute%s ago.", _tmp13_, _tmp11_);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_g_free0 (time);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		time = _tmp14_;
#line 224 "DateLabel.c"
	}
#line 30 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp15_ = timePassed;
#line 30 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	if (_tmp15_ >= ((gint64) 60)) {
#line 230 "DateLabel.c"
		gint64 _tmp16_ = 0LL;
		const gchar* _tmp17_ = NULL;
		gint64 _tmp18_ = 0LL;
		gint64 _tmp19_ = 0LL;
		gchar* _tmp20_ = NULL;
#line 32 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp16_ = timePassed;
#line 32 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		timePassed = _tmp16_ / 60;
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp18_ = timePassed;
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		if (_tmp18_ == ((gint64) 1)) {
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
			_tmp17_ = "";
#line 246 "DateLabel.c"
		} else {
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
			_tmp17_ = "s";
#line 250 "DateLabel.c"
		}
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp19_ = timePassed;
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp20_ = g_strdup_printf ("%lld hour%s ago.", _tmp19_, _tmp17_);
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_g_free0 (time);
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		time = _tmp20_;
#line 260 "DateLabel.c"
	}
#line 35 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp21_ = timePassed;
#line 35 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	if (_tmp21_ >= ((gint64) 24)) {
#line 266 "DateLabel.c"
		gint64 _tmp22_ = 0LL;
		const gchar* _tmp23_ = NULL;
		gint64 _tmp24_ = 0LL;
		gint64 _tmp25_ = 0LL;
		gchar* _tmp26_ = NULL;
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp22_ = timePassed;
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		timePassed = _tmp22_ / 24;
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp24_ = timePassed;
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		if (_tmp24_ == ((gint64) 1)) {
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
			_tmp23_ = "";
#line 282 "DateLabel.c"
		} else {
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
			_tmp23_ = "s";
#line 286 "DateLabel.c"
		}
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp25_ = timePassed;
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp26_ = g_strdup_printf ("%lld day%s ago.", _tmp25_, _tmp23_);
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_g_free0 (time);
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		time = _tmp26_;
#line 296 "DateLabel.c"
	}
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp27_ = timePassed;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	if (_tmp27_ >= ((gint64) 31)) {
#line 302 "DateLabel.c"
		gint64 _tmp28_ = 0LL;
		const gchar* _tmp29_ = NULL;
		gint64 _tmp30_ = 0LL;
		gint64 _tmp31_ = 0LL;
		gchar* _tmp32_ = NULL;
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp28_ = timePassed;
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		timePassed = _tmp28_ / 31;
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp30_ = timePassed;
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		if (_tmp30_ == ((gint64) 1)) {
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
			_tmp29_ = "";
#line 318 "DateLabel.c"
		} else {
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
			_tmp29_ = "s";
#line 322 "DateLabel.c"
		}
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp31_ = timePassed;
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp32_ = g_strdup_printf ("%lld month%s ago.", _tmp31_, _tmp29_);
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_g_free0 (time);
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		time = _tmp32_;
#line 332 "DateLabel.c"
	}
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp33_ = timePassed;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	if (_tmp33_ >= ((gint64) 365)) {
#line 338 "DateLabel.c"
		gint64 _tmp34_ = 0LL;
		const gchar* _tmp35_ = NULL;
		gint64 _tmp36_ = 0LL;
		gint64 _tmp37_ = 0LL;
		gchar* _tmp38_ = NULL;
#line 47 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp34_ = timePassed;
#line 47 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		timePassed = _tmp34_ / 365;
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp36_ = timePassed;
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		if (_tmp36_ == ((gint64) 1)) {
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
			_tmp35_ = "";
#line 354 "DateLabel.c"
		} else {
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
			_tmp35_ = "s";
#line 358 "DateLabel.c"
		}
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp37_ = timePassed;
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_tmp38_ = g_strdup_printf ("%lld year%s ago.", _tmp37_, _tmp35_);
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		_g_free0 (time);
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
		time = _tmp38_;
#line 368 "DateLabel.c"
	}
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp39_ = self->dateLabel;
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp40_ = time;
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp41_ = g_strconcat ("<i>", _tmp40_, NULL);
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp42_ = _tmp41_;
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp43_ = g_strconcat (_tmp42_, "</i>", NULL);
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_tmp44_ = _tmp43_;
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	gtk_label_set_markup (_tmp39_, _tmp44_);
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_g_free0 (_tmp44_);
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_g_free0 (_tmp42_);
#line 53 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) PHOTO_STREAM_WIDGETS_DATE_LABEL_TIME_REFRESH_INTERVAL, ___lambda9__gsource_func, g_object_ref (self), g_object_unref);
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_g_free0 (time);
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_g_date_time_unref0 (currentTime);
#line 394 "DateLabel.c"
}


static void photo_stream_widgets_date_label_class_init (PhotoStreamWidgetsDateLabelClass * klass) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	photo_stream_widgets_date_label_parent_class = g_type_class_peek_parent (klass);
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	G_OBJECT_CLASS (klass)->finalize = photo_stream_widgets_date_label_finalize;
#line 403 "DateLabel.c"
}


static void photo_stream_widgets_date_label_instance_init (PhotoStreamWidgetsDateLabel * self) {
}


static void photo_stream_widgets_date_label_finalize (GObject* obj) {
	PhotoStreamWidgetsDateLabel * self;
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, PhotoStreamWidgetsDateLabel);
#line 7 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_g_object_unref0 (self->dateLabel);
#line 8 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	_g_date_time_unref0 (self->time);
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/DateLabel.vala"
	G_OBJECT_CLASS (photo_stream_widgets_date_label_parent_class)->finalize (obj);
#line 421 "DateLabel.c"
}


GType photo_stream_widgets_date_label_get_type (void) {
	static volatile gsize photo_stream_widgets_date_label_type_id__volatile = 0;
	if (g_once_init_enter (&photo_stream_widgets_date_label_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PhotoStreamWidgetsDateLabelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) photo_stream_widgets_date_label_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PhotoStreamWidgetsDateLabel), 0, (GInstanceInitFunc) photo_stream_widgets_date_label_instance_init, NULL };
		GType photo_stream_widgets_date_label_type_id;
		photo_stream_widgets_date_label_type_id = g_type_register_static (gtk_event_box_get_type (), "PhotoStreamWidgetsDateLabel", &g_define_type_info, 0);
		g_once_init_leave (&photo_stream_widgets_date_label_type_id__volatile, photo_stream_widgets_date_label_type_id);
	}
	return photo_stream_widgets_date_label_type_id__volatile;
}



