/* HashTagBox.c generated by valac 0.26.1.9-22126, the Vala compiler
 * generated from HashTagBox.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define PHOTO_STREAM_WIDGETS_TYPE_HASH_TAG_BOX (photo_stream_widgets_hash_tag_box_get_type ())
#define PHOTO_STREAM_WIDGETS_HASH_TAG_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_WIDGETS_TYPE_HASH_TAG_BOX, PhotoStreamWidgetsHashTagBox))
#define PHOTO_STREAM_WIDGETS_HASH_TAG_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_WIDGETS_TYPE_HASH_TAG_BOX, PhotoStreamWidgetsHashTagBoxClass))
#define PHOTO_STREAM_WIDGETS_IS_HASH_TAG_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_WIDGETS_TYPE_HASH_TAG_BOX))
#define PHOTO_STREAM_WIDGETS_IS_HASH_TAG_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_WIDGETS_TYPE_HASH_TAG_BOX))
#define PHOTO_STREAM_WIDGETS_HASH_TAG_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_WIDGETS_TYPE_HASH_TAG_BOX, PhotoStreamWidgetsHashTagBoxClass))

typedef struct _PhotoStreamWidgetsHashTagBox PhotoStreamWidgetsHashTagBox;
typedef struct _PhotoStreamWidgetsHashTagBoxClass PhotoStreamWidgetsHashTagBoxClass;
typedef struct _PhotoStreamWidgetsHashTagBoxPrivate PhotoStreamWidgetsHashTagBoxPrivate;

#define PHOTO_STREAM_UTILS_TYPE_TAG (photo_stream_utils_tag_get_type ())
#define PHOTO_STREAM_UTILS_TAG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_TAG, PhotoStreamUtilsTag))
#define PHOTO_STREAM_UTILS_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_TAG, PhotoStreamUtilsTagClass))
#define PHOTO_STREAM_UTILS_IS_TAG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_TAG))
#define PHOTO_STREAM_UTILS_IS_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_TAG))
#define PHOTO_STREAM_UTILS_TAG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_TAG, PhotoStreamUtilsTagClass))

typedef struct _PhotoStreamUtilsTag PhotoStreamUtilsTag;
typedef struct _PhotoStreamUtilsTagClass PhotoStreamUtilsTagClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _photo_stream_utils_tag_unref0(var) ((var == NULL) ? NULL : (var = (photo_stream_utils_tag_unref (var), NULL)))
typedef struct _PhotoStreamUtilsTagPrivate PhotoStreamUtilsTagPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _PhotoStreamWidgetsHashTagBox {
	GtkEventBox parent_instance;
	PhotoStreamWidgetsHashTagBoxPrivate * priv;
	GtkBox* box;
	GtkAlignment* hashtagNameAlignment;
	GtkAlignment* mediaCountAlignment;
	GtkLabel* hashtagNameLabel;
	GtkLabel* mediaCountLabel;
	PhotoStreamUtilsTag* tag;
};

struct _PhotoStreamWidgetsHashTagBoxClass {
	GtkEventBoxClass parent_class;
};

struct _PhotoStreamUtilsTag {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsTagPrivate * priv;
	gchar* tag;
	gint64 mediaCount;
};

struct _PhotoStreamUtilsTagClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsTag *self);
};


static gpointer photo_stream_widgets_hash_tag_box_parent_class = NULL;

GType photo_stream_widgets_hash_tag_box_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_tag_ref (gpointer instance);
void photo_stream_utils_tag_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_tag (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_tag (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_tag (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_tag (const GValue* value);
GType photo_stream_utils_tag_get_type (void) G_GNUC_CONST;
enum  {
	PHOTO_STREAM_WIDGETS_HASH_TAG_BOX_DUMMY_PROPERTY
};
PhotoStreamWidgetsHashTagBox* photo_stream_widgets_hash_tag_box_new (PhotoStreamUtilsTag* tag);
PhotoStreamWidgetsHashTagBox* photo_stream_widgets_hash_tag_box_construct (GType object_type, PhotoStreamUtilsTag* tag);
gchar* wrapInTags (const gchar* original);
static void photo_stream_widgets_hash_tag_box_finalize (GObject* obj);


static gpointer _photo_stream_utils_tag_ref0 (gpointer self) {
#line 17 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	return self ? photo_stream_utils_tag_ref (self) : NULL;
#line 91 "HashTagBox.c"
}


PhotoStreamWidgetsHashTagBox* photo_stream_widgets_hash_tag_box_construct (GType object_type, PhotoStreamUtilsTag* tag) {
	PhotoStreamWidgetsHashTagBox * self = NULL;
	PhotoStreamUtilsTag* _tmp0_ = NULL;
	PhotoStreamUtilsTag* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	GtkAlignment* _tmp3_ = NULL;
	GtkAlignment* _tmp4_ = NULL;
	GtkAlignment* _tmp5_ = NULL;
	GtkAlignment* _tmp6_ = NULL;
	GtkAlignment* _tmp7_ = NULL;
	GtkLabel* _tmp8_ = NULL;
	GtkLabel* _tmp9_ = NULL;
	PhotoStreamUtilsTag* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	GtkAlignment* _tmp16_ = NULL;
	GtkLabel* _tmp17_ = NULL;
	GtkBox* _tmp18_ = NULL;
	GtkAlignment* _tmp19_ = NULL;
	GtkAlignment* _tmp20_ = NULL;
	GtkAlignment* _tmp21_ = NULL;
	GtkAlignment* _tmp22_ = NULL;
	GtkAlignment* _tmp23_ = NULL;
	GtkAlignment* _tmp24_ = NULL;
	GtkLabel* _tmp25_ = NULL;
	GtkLabel* _tmp26_ = NULL;
	PhotoStreamUtilsTag* _tmp27_ = NULL;
	gint64 _tmp28_ = 0LL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	GtkAlignment* _tmp35_ = NULL;
	GtkLabel* _tmp36_ = NULL;
	GtkBox* _tmp37_ = NULL;
	GtkAlignment* _tmp38_ = NULL;
	GtkBox* _tmp39_ = NULL;
#line 15 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_return_val_if_fail (tag != NULL, NULL);
#line 15 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	self = (PhotoStreamWidgetsHashTagBox*) g_object_new (object_type, NULL);
#line 17 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp0_ = tag;
#line 17 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp1_ = _photo_stream_utils_tag_ref0 (_tmp0_);
#line 17 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_photo_stream_utils_tag_unref0 (self->tag);
#line 17 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	self->tag = _tmp1_;
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp2_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_ref_sink (_tmp2_);
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_object_unref0 (self->box);
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	self->box = _tmp2_;
#line 21 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp3_ = (GtkAlignment*) gtk_alignment_new ((gfloat) 0, (gfloat) 0, (gfloat) 1, (gfloat) 1);
#line 21 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_ref_sink (_tmp3_);
#line 21 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_object_unref0 (self->hashtagNameAlignment);
#line 21 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	self->hashtagNameAlignment = _tmp3_;
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp4_ = self->hashtagNameAlignment;
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_set (_tmp4_, "top-padding", (guint) 2, NULL);
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp5_ = self->hashtagNameAlignment;
#line 23 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_set (_tmp5_, "right-padding", (guint) 6, NULL);
#line 24 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp6_ = self->hashtagNameAlignment;
#line 24 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_set (_tmp6_, "bottom-padding", (guint) 2, NULL);
#line 25 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp7_ = self->hashtagNameAlignment;
#line 25 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_set (_tmp7_, "left-padding", (guint) 6, NULL);
#line 27 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp8_ = (GtkLabel*) gtk_label_new ("");
#line 27 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_ref_sink (_tmp8_);
#line 27 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_object_unref0 (self->hashtagNameLabel);
#line 27 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	self->hashtagNameLabel = _tmp8_;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp9_ = self->hashtagNameLabel;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp10_ = tag;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp11_ = _tmp10_->tag;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp12_ = g_strconcat ("#", _tmp11_, NULL);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp13_ = _tmp12_;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp14_ = wrapInTags (_tmp13_);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp15_ = _tmp14_;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	gtk_label_set_markup (_tmp9_, _tmp15_);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_free0 (_tmp15_);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_free0 (_tmp13_);
#line 30 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp16_ = self->hashtagNameAlignment;
#line 30 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp17_ = self->hashtagNameLabel;
#line 30 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	gtk_container_add ((GtkContainer*) _tmp16_, (GtkWidget*) _tmp17_);
#line 31 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp18_ = self->box;
#line 31 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp19_ = self->hashtagNameAlignment;
#line 31 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	gtk_box_pack_start (_tmp18_, (GtkWidget*) _tmp19_, FALSE, TRUE, (guint) 0);
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp20_ = (GtkAlignment*) gtk_alignment_new ((gfloat) 0, (gfloat) 0, (gfloat) 1, (gfloat) 1);
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_ref_sink (_tmp20_);
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_object_unref0 (self->mediaCountAlignment);
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	self->mediaCountAlignment = _tmp20_;
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp21_ = self->mediaCountAlignment;
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_set (_tmp21_, "top-padding", (guint) 2, NULL);
#line 35 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp22_ = self->mediaCountAlignment;
#line 35 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_set (_tmp22_, "right-padding", (guint) 6, NULL);
#line 36 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp23_ = self->mediaCountAlignment;
#line 36 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_set (_tmp23_, "bottom-padding", (guint) 2, NULL);
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp24_ = self->mediaCountAlignment;
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_set (_tmp24_, "left-padding", (guint) 6, NULL);
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp25_ = (GtkLabel*) gtk_label_new ("");
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	g_object_ref_sink (_tmp25_);
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_object_unref0 (self->mediaCountLabel);
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	self->mediaCountLabel = _tmp25_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp26_ = self->mediaCountLabel;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp27_ = tag;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp28_ = _tmp27_->mediaCount;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp29_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp28_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp30_ = _tmp29_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp31_ = g_strconcat ("<b>", _tmp30_, NULL);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp32_ = _tmp31_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp33_ = g_strconcat (_tmp32_, "</b> posts.", NULL);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp34_ = _tmp33_;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	gtk_label_set_markup (_tmp26_, _tmp34_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_free0 (_tmp34_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_free0 (_tmp32_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_free0 (_tmp30_);
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp35_ = self->mediaCountAlignment;
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp36_ = self->mediaCountLabel;
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	gtk_container_add ((GtkContainer*) _tmp35_, (GtkWidget*) _tmp36_);
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp37_ = self->box;
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp38_ = self->mediaCountAlignment;
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	gtk_box_pack_end (_tmp37_, (GtkWidget*) _tmp38_, FALSE, TRUE, (guint) 0);
#line 44 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_tmp39_ = self->box;
#line 44 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp39_);
#line 15 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	return self;
#line 297 "HashTagBox.c"
}


PhotoStreamWidgetsHashTagBox* photo_stream_widgets_hash_tag_box_new (PhotoStreamUtilsTag* tag) {
#line 15 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	return photo_stream_widgets_hash_tag_box_construct (PHOTO_STREAM_WIDGETS_TYPE_HASH_TAG_BOX, tag);
#line 304 "HashTagBox.c"
}


static void photo_stream_widgets_hash_tag_box_class_init (PhotoStreamWidgetsHashTagBoxClass * klass) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	photo_stream_widgets_hash_tag_box_parent_class = g_type_class_peek_parent (klass);
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	G_OBJECT_CLASS (klass)->finalize = photo_stream_widgets_hash_tag_box_finalize;
#line 313 "HashTagBox.c"
}


static void photo_stream_widgets_hash_tag_box_instance_init (PhotoStreamWidgetsHashTagBox * self) {
}


static void photo_stream_widgets_hash_tag_box_finalize (GObject* obj) {
	PhotoStreamWidgetsHashTagBox * self;
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PHOTO_STREAM_WIDGETS_TYPE_HASH_TAG_BOX, PhotoStreamWidgetsHashTagBox);
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_object_unref0 (self->box);
#line 7 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_object_unref0 (self->hashtagNameAlignment);
#line 8 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_object_unref0 (self->mediaCountAlignment);
#line 10 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_object_unref0 (self->hashtagNameLabel);
#line 11 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_g_object_unref0 (self->mediaCountLabel);
#line 13 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	_photo_stream_utils_tag_unref0 (self->tag);
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/HashTagBox.vala"
	G_OBJECT_CLASS (photo_stream_widgets_hash_tag_box_parent_class)->finalize (obj);
#line 339 "HashTagBox.c"
}


GType photo_stream_widgets_hash_tag_box_get_type (void) {
	static volatile gsize photo_stream_widgets_hash_tag_box_type_id__volatile = 0;
	if (g_once_init_enter (&photo_stream_widgets_hash_tag_box_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PhotoStreamWidgetsHashTagBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) photo_stream_widgets_hash_tag_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PhotoStreamWidgetsHashTagBox), 0, (GInstanceInitFunc) photo_stream_widgets_hash_tag_box_instance_init, NULL };
		GType photo_stream_widgets_hash_tag_box_type_id;
		photo_stream_widgets_hash_tag_box_type_id = g_type_register_static (gtk_event_box_get_type (), "PhotoStreamWidgetsHashTagBox", &g_define_type_info, 0);
		g_once_init_leave (&photo_stream_widgets_hash_tag_box_type_id__volatile, photo_stream_widgets_hash_tag_box_type_id);
	}
	return photo_stream_widgets_hash_tag_box_type_id__volatile;
}



