/* NewsList.c generated by valac 0.26.1.9-22126, the Vala compiler
 * generated from NewsList.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define PHOTO_STREAM_WIDGETS_TYPE_NEWS_LIST (photo_stream_widgets_news_list_get_type ())
#define PHOTO_STREAM_WIDGETS_NEWS_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_WIDGETS_TYPE_NEWS_LIST, PhotoStreamWidgetsNewsList))
#define PHOTO_STREAM_WIDGETS_NEWS_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_WIDGETS_TYPE_NEWS_LIST, PhotoStreamWidgetsNewsListClass))
#define PHOTO_STREAM_WIDGETS_IS_NEWS_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_WIDGETS_TYPE_NEWS_LIST))
#define PHOTO_STREAM_WIDGETS_IS_NEWS_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_WIDGETS_TYPE_NEWS_LIST))
#define PHOTO_STREAM_WIDGETS_NEWS_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_WIDGETS_TYPE_NEWS_LIST, PhotoStreamWidgetsNewsListClass))

typedef struct _PhotoStreamWidgetsNewsList PhotoStreamWidgetsNewsList;
typedef struct _PhotoStreamWidgetsNewsListClass PhotoStreamWidgetsNewsListClass;
typedef struct _PhotoStreamWidgetsNewsListPrivate PhotoStreamWidgetsNewsListPrivate;

#define PHOTO_STREAM_WIDGETS_TYPE_NEWS_BOX (photo_stream_widgets_news_box_get_type ())
#define PHOTO_STREAM_WIDGETS_NEWS_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_WIDGETS_TYPE_NEWS_BOX, PhotoStreamWidgetsNewsBox))
#define PHOTO_STREAM_WIDGETS_NEWS_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_WIDGETS_TYPE_NEWS_BOX, PhotoStreamWidgetsNewsBoxClass))
#define PHOTO_STREAM_WIDGETS_IS_NEWS_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_WIDGETS_TYPE_NEWS_BOX))
#define PHOTO_STREAM_WIDGETS_IS_NEWS_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_WIDGETS_TYPE_NEWS_BOX))
#define PHOTO_STREAM_WIDGETS_NEWS_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_WIDGETS_TYPE_NEWS_BOX, PhotoStreamWidgetsNewsBoxClass))

typedef struct _PhotoStreamWidgetsNewsBox PhotoStreamWidgetsNewsBox;
typedef struct _PhotoStreamWidgetsNewsBoxClass PhotoStreamWidgetsNewsBoxClass;
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY (photo_stream_utils_news_activity_get_type ())
#define PHOTO_STREAM_UTILS_NEWS_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY, PhotoStreamUtilsNewsActivity))
#define PHOTO_STREAM_UTILS_NEWS_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY, PhotoStreamUtilsNewsActivityClass))
#define PHOTO_STREAM_UTILS_IS_NEWS_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY))
#define PHOTO_STREAM_UTILS_IS_NEWS_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY))
#define PHOTO_STREAM_UTILS_NEWS_ACTIVITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_NEWS_ACTIVITY, PhotoStreamUtilsNewsActivityClass))

typedef struct _PhotoStreamUtilsNewsActivity PhotoStreamUtilsNewsActivity;
typedef struct _PhotoStreamUtilsNewsActivityClass PhotoStreamUtilsNewsActivityClass;
typedef struct _PhotoStreamWidgetsNewsBoxPrivate PhotoStreamWidgetsNewsBoxPrivate;

#define PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL (photo_stream_widgets_date_label_get_type ())
#define PHOTO_STREAM_WIDGETS_DATE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, PhotoStreamWidgetsDateLabel))
#define PHOTO_STREAM_WIDGETS_DATE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, PhotoStreamWidgetsDateLabelClass))
#define PHOTO_STREAM_WIDGETS_IS_DATE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL))
#define PHOTO_STREAM_WIDGETS_IS_DATE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL))
#define PHOTO_STREAM_WIDGETS_DATE_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, PhotoStreamWidgetsDateLabelClass))

typedef struct _PhotoStreamWidgetsDateLabel PhotoStreamWidgetsDateLabel;
typedef struct _PhotoStreamWidgetsDateLabelClass PhotoStreamWidgetsDateLabelClass;
typedef struct _PhotoStreamUtilsNewsActivityPrivate PhotoStreamUtilsNewsActivityPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

struct _PhotoStreamWidgetsNewsList {
	GtkBox parent_instance;
	PhotoStreamWidgetsNewsListPrivate * priv;
	GList* boxes;
	GtkListBox* newsList;
	GtkScrolledWindow* newsWindow;
};

struct _PhotoStreamWidgetsNewsListClass {
	GtkBoxClass parent_class;
};

struct _PhotoStreamWidgetsNewsBox {
	GtkEventBox parent_instance;
	PhotoStreamWidgetsNewsBoxPrivate * priv;
	GtkBox* box;
	GtkImage* avatarImage;
	GtkImage* postImage;
	GtkBox* textBox;
	GtkLabel* commentLabel;
	PhotoStreamWidgetsDateLabel* dateLabel;
	GtkEventBox* avatarBox;
	GtkEventBox* postImageBox;
	GtkAlignment* avatarAlignment;
	GtkAlignment* commentAlignment;
	GtkAlignment* dateAlignment;
	GtkAlignment* postImageAlignment;
	gint AVATAR_SIZE;
	PhotoStreamUtilsNewsActivity* activity;
};

struct _PhotoStreamWidgetsNewsBoxClass {
	GtkEventBoxClass parent_class;
};

struct _PhotoStreamUtilsNewsActivity {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsNewsActivityPrivate * priv;
	gchar* username;
	gchar* userProfilePicture;
	gchar* imagePicture;
	gchar* activityType;
	gchar* postId;
	GDateTime* time;
	gchar* comment;
};

struct _PhotoStreamUtilsNewsActivityClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsNewsActivity *self);
};


static gpointer photo_stream_widgets_news_list_parent_class = NULL;

GType photo_stream_widgets_news_list_get_type (void) G_GNUC_CONST;
GType photo_stream_widgets_news_box_get_type (void) G_GNUC_CONST;
enum  {
	PHOTO_STREAM_WIDGETS_NEWS_LIST_DUMMY_PROPERTY
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
PhotoStreamWidgetsNewsList* photo_stream_widgets_news_list_new (void);
PhotoStreamWidgetsNewsList* photo_stream_widgets_news_list_construct (GType object_type);
gpointer photo_stream_utils_news_activity_ref (gpointer instance);
void photo_stream_utils_news_activity_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_news_activity (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_news_activity (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_news_activity (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_news_activity (const GValue* value);
GType photo_stream_utils_news_activity_get_type (void) G_GNUC_CONST;
void photo_stream_widgets_news_list_append (PhotoStreamWidgetsNewsList* self, PhotoStreamUtilsNewsActivity* post);
PhotoStreamWidgetsNewsBox* photo_stream_widgets_news_box_new (PhotoStreamUtilsNewsActivity* activity);
PhotoStreamWidgetsNewsBox* photo_stream_widgets_news_box_construct (GType object_type, PhotoStreamUtilsNewsActivity* activity);
gboolean photo_stream_widgets_news_list_contains (PhotoStreamWidgetsNewsList* self, PhotoStreamUtilsNewsActivity* activity);
GType photo_stream_widgets_date_label_get_type (void) G_GNUC_CONST;
void photo_stream_widgets_news_list_prepend (PhotoStreamWidgetsNewsList* self, PhotoStreamUtilsNewsActivity* post);
void photo_stream_widgets_news_list_clear (PhotoStreamWidgetsNewsList* self);
static void photo_stream_widgets_news_list_finalize (GObject* obj);


static void _g_object_unref0_ (gpointer var) {
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 145 "NewsList.c"
}


static void _g_list_free__g_object_unref0_ (GList* self) {
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_list_free (self);
#line 154 "NewsList.c"
}


PhotoStreamWidgetsNewsList* photo_stream_widgets_news_list_construct (GType object_type) {
	PhotoStreamWidgetsNewsList * self = NULL;
	GtkListBox* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	GtkListBox* _tmp2_ = NULL;
	GtkScrolledWindow* _tmp3_ = NULL;
	GtkScrolledWindow* _tmp4_ = NULL;
	GtkScrolledWindow* _tmp5_ = NULL;
	GtkListBox* _tmp6_ = NULL;
	GtkScrolledWindow* _tmp7_ = NULL;
	GtkListBox* _tmp8_ = NULL;
	GtkScrolledWindow* _tmp9_ = NULL;
#line 12 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	self = (PhotoStreamWidgetsNewsList*) g_object_new (object_type, NULL);
#line 14 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	__g_list_free__g_object_unref0_0 (self->boxes);
#line 14 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	self->boxes = NULL;
#line 16 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp0_ = (GtkListBox*) gtk_list_box_new ();
#line 16 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_object_ref_sink (_tmp0_);
#line 16 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_g_object_unref0 (self->newsList);
#line 16 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	self->newsList = _tmp0_;
#line 17 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp1_ = self->newsList;
#line 17 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	gtk_list_box_set_selection_mode (_tmp1_, GTK_SELECTION_NONE);
#line 18 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp2_ = self->newsList;
#line 18 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	gtk_list_box_set_activate_on_single_click (_tmp2_, FALSE);
#line 20 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp3_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 20 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_object_ref_sink (_tmp3_);
#line 20 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_g_object_unref0 (self->newsWindow);
#line 20 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	self->newsWindow = _tmp3_;
#line 21 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp4_ = self->newsWindow;
#line 21 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	gtk_scrolled_window_set_policy (_tmp4_, GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp5_ = self->newsWindow;
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp6_ = self->newsList;
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	gtk_scrolled_window_add_with_viewport (_tmp5_, (GtkWidget*) _tmp6_);
#line 24 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp7_ = self->newsWindow;
#line 24 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp8_ = self->newsList;
#line 24 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	gtk_scrolled_window_add_with_viewport (_tmp7_, (GtkWidget*) _tmp8_);
#line 25 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp9_ = self->newsWindow;
#line 25 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp9_, TRUE, TRUE, (guint) 0);
#line 12 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	return self;
#line 222 "NewsList.c"
}


PhotoStreamWidgetsNewsList* photo_stream_widgets_news_list_new (void) {
#line 12 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	return photo_stream_widgets_news_list_construct (PHOTO_STREAM_WIDGETS_TYPE_NEWS_LIST);
#line 229 "NewsList.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	return self ? g_object_ref (self) : NULL;
#line 236 "NewsList.c"
}


void photo_stream_widgets_news_list_append (PhotoStreamWidgetsNewsList* self, PhotoStreamUtilsNewsActivity* post) {
	GtkSeparator* separator = NULL;
	GtkSeparator* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	PhotoStreamWidgetsNewsBox* box = NULL;
	PhotoStreamUtilsNewsActivity* _tmp2_ = NULL;
	PhotoStreamWidgetsNewsBox* _tmp3_ = NULL;
	GtkListBox* _tmp4_ = NULL;
	PhotoStreamWidgetsNewsBox* _tmp5_ = NULL;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_return_if_fail (self != NULL);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_return_if_fail (post != NULL);
#line 30 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp0_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
#line 30 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_object_ref_sink (_tmp0_);
#line 30 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	separator = _tmp0_;
#line 31 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp1_ = self->newsList;
#line 31 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	gtk_list_box_prepend (_tmp1_, (GtkWidget*) separator);
#line 32 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp2_ = post;
#line 32 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp3_ = photo_stream_widgets_news_box_new (_tmp2_);
#line 32 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_object_ref_sink (_tmp3_);
#line 32 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	box = _tmp3_;
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp4_ = self->newsList;
#line 33 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	gtk_list_box_prepend (_tmp4_, (GtkWidget*) box);
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp5_ = _g_object_ref0 (box);
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	self->boxes = g_list_append (self->boxes, _tmp5_);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_g_object_unref0 (box);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_g_object_unref0 (separator);
#line 283 "NewsList.c"
}


static gchar* g_date_time_to_string (GDateTime* self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
#line 2586 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 2587 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp0_ = g_date_time_format (self, "%FT%H:%M:%S%z");
#line 2587 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	result = _tmp0_;
#line 2587 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	return result;
#line 298 "NewsList.c"
}


gboolean photo_stream_widgets_news_list_contains (PhotoStreamWidgetsNewsList* self, PhotoStreamUtilsNewsActivity* activity) {
	gboolean result = FALSE;
	GList* _tmp0_ = NULL;
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_return_val_if_fail (activity != NULL, FALSE);
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp0_ = self->boxes;
#line 311 "NewsList.c"
	{
		GList* activityInList_collection = NULL;
		GList* activityInList_it = NULL;
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
		activityInList_collection = _tmp0_;
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
		for (activityInList_it = activityInList_collection; activityInList_it != NULL; activityInList_it = activityInList_it->next) {
#line 319 "NewsList.c"
			PhotoStreamWidgetsNewsBox* _tmp1_ = NULL;
			PhotoStreamWidgetsNewsBox* activityInList = NULL;
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
			_tmp1_ = _g_object_ref0 ((PhotoStreamWidgetsNewsBox*) activityInList_it->data);
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
			activityInList = _tmp1_;
#line 326 "NewsList.c"
			{
				gboolean _tmp2_ = FALSE;
				gboolean _tmp3_ = FALSE;
				PhotoStreamWidgetsNewsBox* _tmp4_ = NULL;
				PhotoStreamUtilsNewsActivity* _tmp5_ = NULL;
				GDateTime* _tmp6_ = NULL;
				gchar* _tmp7_ = NULL;
				gchar* _tmp8_ = NULL;
				PhotoStreamUtilsNewsActivity* _tmp9_ = NULL;
				GDateTime* _tmp10_ = NULL;
				gchar* _tmp11_ = NULL;
				gchar* _tmp12_ = NULL;
				gboolean _tmp13_ = FALSE;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp4_ = activityInList;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp5_ = _tmp4_->activity;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp6_ = _tmp5_->time;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp7_ = g_date_time_to_string (_tmp6_);
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp8_ = _tmp7_;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp9_ = activity;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp10_ = _tmp9_->time;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp11_ = g_date_time_to_string (_tmp10_);
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp12_ = _tmp11_;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp13_ = g_strcmp0 (_tmp8_, _tmp12_) == 0;
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_g_free0 (_tmp12_);
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_g_free0 (_tmp8_);
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				if (_tmp13_) {
#line 366 "NewsList.c"
					PhotoStreamWidgetsNewsBox* _tmp14_ = NULL;
					PhotoStreamUtilsNewsActivity* _tmp15_ = NULL;
					const gchar* _tmp16_ = NULL;
					PhotoStreamUtilsNewsActivity* _tmp17_ = NULL;
					const gchar* _tmp18_ = NULL;
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp14_ = activityInList;
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp15_ = _tmp14_->activity;
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp16_ = _tmp15_->username;
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp17_ = activity;
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp18_ = _tmp17_->username;
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp3_ = g_strcmp0 (_tmp16_, _tmp18_) == 0;
#line 384 "NewsList.c"
				} else {
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp3_ = FALSE;
#line 388 "NewsList.c"
				}
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				if (_tmp3_) {
#line 392 "NewsList.c"
					PhotoStreamWidgetsNewsBox* _tmp19_ = NULL;
					PhotoStreamUtilsNewsActivity* _tmp20_ = NULL;
					const gchar* _tmp21_ = NULL;
					PhotoStreamUtilsNewsActivity* _tmp22_ = NULL;
					const gchar* _tmp23_ = NULL;
#line 47 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp19_ = activityInList;
#line 47 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp20_ = _tmp19_->activity;
#line 47 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp21_ = _tmp20_->activityType;
#line 47 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp22_ = activity;
#line 47 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp23_ = _tmp22_->activityType;
#line 47 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp2_ = g_strcmp0 (_tmp21_, _tmp23_) == 0;
#line 410 "NewsList.c"
				} else {
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_tmp2_ = FALSE;
#line 414 "NewsList.c"
				}
#line 45 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				if (_tmp2_) {
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					result = TRUE;
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					_g_object_unref0 (activityInList);
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
					return result;
#line 424 "NewsList.c"
				}
#line 39 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_g_object_unref0 (activityInList);
#line 428 "NewsList.c"
			}
		}
	}
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	result = FALSE;
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	return result;
#line 436 "NewsList.c"
}


void photo_stream_widgets_news_list_prepend (PhotoStreamWidgetsNewsList* self, PhotoStreamUtilsNewsActivity* post) {
	GtkSeparator* separator = NULL;
	GtkSeparator* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	GtkListBox* _tmp2_ = NULL;
	GList* _tmp3_ = NULL;
	GList* _tmp4_ = NULL;
	guint _tmp5_ = 0U;
	PhotoStreamWidgetsNewsBox* box = NULL;
	PhotoStreamUtilsNewsActivity* _tmp6_ = NULL;
	PhotoStreamWidgetsNewsBox* _tmp7_ = NULL;
	GtkListBox* _tmp8_ = NULL;
	GtkListBox* _tmp9_ = NULL;
	GList* _tmp10_ = NULL;
	GList* _tmp11_ = NULL;
	guint _tmp12_ = 0U;
	PhotoStreamWidgetsNewsBox* _tmp13_ = NULL;
#line 54 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_return_if_fail (self != NULL);
#line 54 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_return_if_fail (post != NULL);
#line 56 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp0_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
#line 56 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_object_ref_sink (_tmp0_);
#line 56 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	separator = _tmp0_;
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp1_ = self->newsList;
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp2_ = self->newsList;
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp3_ = gtk_container_get_children ((GtkContainer*) _tmp2_);
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp4_ = _tmp3_;
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp5_ = g_list_length (_tmp4_);
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	gtk_list_box_insert (_tmp1_, (GtkWidget*) separator, ((gint) _tmp5_) - 1);
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_g_list_free0 (_tmp4_);
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp6_ = post;
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp7_ = photo_stream_widgets_news_box_new (_tmp6_);
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_object_ref_sink (_tmp7_);
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	box = _tmp7_;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp8_ = self->newsList;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp9_ = self->newsList;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp10_ = gtk_container_get_children ((GtkContainer*) _tmp9_);
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp11_ = _tmp10_;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp12_ = g_list_length (_tmp11_);
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	gtk_list_box_insert (_tmp8_, (GtkWidget*) box, ((gint) _tmp12_) - 1);
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_g_list_free0 (_tmp11_);
#line 60 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp13_ = _g_object_ref0 (box);
#line 60 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	self->boxes = g_list_append (self->boxes, _tmp13_);
#line 54 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_g_object_unref0 (box);
#line 54 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_g_object_unref0 (separator);
#line 511 "NewsList.c"
}


void photo_stream_widgets_news_list_clear (PhotoStreamWidgetsNewsList* self) {
	GtkListBox* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
#line 63 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	g_return_if_fail (self != NULL);
#line 65 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp0_ = self->newsList;
#line 65 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_tmp1_ = gtk_container_get_children ((GtkContainer*) _tmp0_);
#line 524 "NewsList.c"
	{
		GList* child_collection = NULL;
		GList* child_it = NULL;
#line 65 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
		child_collection = _tmp1_;
#line 65 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
		for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
#line 532 "NewsList.c"
			GtkWidget* child = NULL;
#line 65 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
			child = (GtkWidget*) child_it->data;
#line 536 "NewsList.c"
			{
				GtkListBox* _tmp2_ = NULL;
				GtkWidget* _tmp3_ = NULL;
#line 66 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp2_ = self->newsList;
#line 66 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				_tmp3_ = child;
#line 66 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
				gtk_container_remove ((GtkContainer*) _tmp2_, _tmp3_);
#line 546 "NewsList.c"
			}
		}
#line 65 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
		_g_list_free0 (child_collection);
#line 551 "NewsList.c"
	}
#line 67 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	__g_list_free__g_object_unref0_0 (self->boxes);
#line 67 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	self->boxes = NULL;
#line 557 "NewsList.c"
}


static void photo_stream_widgets_news_list_class_init (PhotoStreamWidgetsNewsListClass * klass) {
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	photo_stream_widgets_news_list_parent_class = g_type_class_peek_parent (klass);
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	G_OBJECT_CLASS (klass)->finalize = photo_stream_widgets_news_list_finalize;
#line 566 "NewsList.c"
}


static void photo_stream_widgets_news_list_instance_init (PhotoStreamWidgetsNewsList * self) {
}


static void photo_stream_widgets_news_list_finalize (GObject* obj) {
	PhotoStreamWidgetsNewsList * self;
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PHOTO_STREAM_WIDGETS_TYPE_NEWS_LIST, PhotoStreamWidgetsNewsList);
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	__g_list_free__g_object_unref0_0 (self->boxes);
#line 9 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_g_object_unref0 (self->newsList);
#line 10 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	_g_object_unref0 (self->newsWindow);
#line 3 "/all/Documents/Programming/vala/photostream/src/Widgets/NewsList.vala"
	G_OBJECT_CLASS (photo_stream_widgets_news_list_parent_class)->finalize (obj);
#line 586 "NewsList.c"
}


GType photo_stream_widgets_news_list_get_type (void) {
	static volatile gsize photo_stream_widgets_news_list_type_id__volatile = 0;
	if (g_once_init_enter (&photo_stream_widgets_news_list_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PhotoStreamWidgetsNewsListClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) photo_stream_widgets_news_list_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PhotoStreamWidgetsNewsList), 0, (GInstanceInitFunc) photo_stream_widgets_news_list_instance_init, NULL };
		GType photo_stream_widgets_news_list_type_id;
		photo_stream_widgets_news_list_type_id = g_type_register_static (gtk_box_get_type (), "PhotoStreamWidgetsNewsList", &g_define_type_info, 0);
		g_once_init_leave (&photo_stream_widgets_news_list_type_id__volatile, photo_stream_widgets_news_list_type_id);
	}
	return photo_stream_widgets_news_list_type_id__volatile;
}



