/* PostList.c generated by valac 0.26.1.9-22126, the Vala compiler
 * generated from PostList.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <granite.h>
#include <gdk/gdk.h>


#define PHOTO_STREAM_WIDGETS_TYPE_POST_LIST (photo_stream_widgets_post_list_get_type ())
#define PHOTO_STREAM_WIDGETS_POST_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_WIDGETS_TYPE_POST_LIST, PhotoStreamWidgetsPostList))
#define PHOTO_STREAM_WIDGETS_POST_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_WIDGETS_TYPE_POST_LIST, PhotoStreamWidgetsPostListClass))
#define PHOTO_STREAM_WIDGETS_IS_POST_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_WIDGETS_TYPE_POST_LIST))
#define PHOTO_STREAM_WIDGETS_IS_POST_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_WIDGETS_TYPE_POST_LIST))
#define PHOTO_STREAM_WIDGETS_POST_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_WIDGETS_TYPE_POST_LIST, PhotoStreamWidgetsPostListClass))

typedef struct _PhotoStreamWidgetsPostList PhotoStreamWidgetsPostList;
typedef struct _PhotoStreamWidgetsPostListClass PhotoStreamWidgetsPostListClass;
typedef struct _PhotoStreamWidgetsPostListPrivate PhotoStreamWidgetsPostListPrivate;

#define PHOTO_STREAM_WIDGETS_TYPE_POST_BOX (photo_stream_widgets_post_box_get_type ())
#define PHOTO_STREAM_WIDGETS_POST_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_WIDGETS_TYPE_POST_BOX, PhotoStreamWidgetsPostBox))
#define PHOTO_STREAM_WIDGETS_POST_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_WIDGETS_TYPE_POST_BOX, PhotoStreamWidgetsPostBoxClass))
#define PHOTO_STREAM_WIDGETS_IS_POST_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_WIDGETS_TYPE_POST_BOX))
#define PHOTO_STREAM_WIDGETS_IS_POST_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_WIDGETS_TYPE_POST_BOX))
#define PHOTO_STREAM_WIDGETS_POST_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_WIDGETS_TYPE_POST_BOX, PhotoStreamWidgetsPostBoxClass))

typedef struct _PhotoStreamWidgetsPostBox PhotoStreamWidgetsPostBox;
typedef struct _PhotoStreamWidgetsPostBoxClass PhotoStreamWidgetsPostBoxClass;
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

#define PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO (photo_stream_utils_media_info_get_type ())
#define PHOTO_STREAM_UTILS_MEDIA_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO, PhotoStreamUtilsMediaInfo))
#define PHOTO_STREAM_UTILS_MEDIA_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO, PhotoStreamUtilsMediaInfoClass))
#define PHOTO_STREAM_UTILS_IS_MEDIA_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO))
#define PHOTO_STREAM_UTILS_IS_MEDIA_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO))
#define PHOTO_STREAM_UTILS_MEDIA_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA_INFO, PhotoStreamUtilsMediaInfoClass))

typedef struct _PhotoStreamUtilsMediaInfo PhotoStreamUtilsMediaInfo;
typedef struct _PhotoStreamUtilsMediaInfoClass PhotoStreamUtilsMediaInfoClass;
typedef struct _PhotoStreamWidgetsPostBoxPrivate PhotoStreamWidgetsPostBoxPrivate;

#define PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL (photo_stream_widgets_date_label_get_type ())
#define PHOTO_STREAM_WIDGETS_DATE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, PhotoStreamWidgetsDateLabel))
#define PHOTO_STREAM_WIDGETS_DATE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, PhotoStreamWidgetsDateLabelClass))
#define PHOTO_STREAM_WIDGETS_IS_DATE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL))
#define PHOTO_STREAM_WIDGETS_IS_DATE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL))
#define PHOTO_STREAM_WIDGETS_DATE_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_WIDGETS_TYPE_DATE_LABEL, PhotoStreamWidgetsDateLabelClass))

typedef struct _PhotoStreamWidgetsDateLabel PhotoStreamWidgetsDateLabel;
typedef struct _PhotoStreamWidgetsDateLabelClass PhotoStreamWidgetsDateLabelClass;

#define PHOTO_STREAM_WIDGETS_TYPE_COMMENTS_LIST (photo_stream_widgets_comments_list_get_type ())
#define PHOTO_STREAM_WIDGETS_COMMENTS_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_WIDGETS_TYPE_COMMENTS_LIST, PhotoStreamWidgetsCommentsList))
#define PHOTO_STREAM_WIDGETS_COMMENTS_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_WIDGETS_TYPE_COMMENTS_LIST, PhotoStreamWidgetsCommentsListClass))
#define PHOTO_STREAM_WIDGETS_IS_COMMENTS_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_WIDGETS_TYPE_COMMENTS_LIST))
#define PHOTO_STREAM_WIDGETS_IS_COMMENTS_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_WIDGETS_TYPE_COMMENTS_LIST))
#define PHOTO_STREAM_WIDGETS_COMMENTS_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_WIDGETS_TYPE_COMMENTS_LIST, PhotoStreamWidgetsCommentsListClass))

typedef struct _PhotoStreamWidgetsCommentsList PhotoStreamWidgetsCommentsList;
typedef struct _PhotoStreamWidgetsCommentsListClass PhotoStreamWidgetsCommentsListClass;
typedef struct _PhotoStreamUtilsMediaInfoPrivate PhotoStreamUtilsMediaInfoPrivate;

#define PHOTO_STREAM_UTILS_TYPE_COMMENT (photo_stream_utils_comment_get_type ())
#define PHOTO_STREAM_UTILS_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_COMMENT, PhotoStreamUtilsComment))
#define PHOTO_STREAM_UTILS_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_COMMENT, PhotoStreamUtilsCommentClass))
#define PHOTO_STREAM_UTILS_IS_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_COMMENT))
#define PHOTO_STREAM_UTILS_IS_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_COMMENT))
#define PHOTO_STREAM_UTILS_COMMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_COMMENT, PhotoStreamUtilsCommentClass))

typedef struct _PhotoStreamUtilsComment PhotoStreamUtilsComment;
typedef struct _PhotoStreamUtilsCommentClass PhotoStreamUtilsCommentClass;

#define PHOTO_STREAM_UTILS_TYPE_LOCATION (photo_stream_utils_location_get_type ())
#define PHOTO_STREAM_UTILS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_LOCATION, PhotoStreamUtilsLocation))
#define PHOTO_STREAM_UTILS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_LOCATION, PhotoStreamUtilsLocationClass))
#define PHOTO_STREAM_UTILS_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_LOCATION))
#define PHOTO_STREAM_UTILS_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_LOCATION))
#define PHOTO_STREAM_UTILS_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_LOCATION, PhotoStreamUtilsLocationClass))

typedef struct _PhotoStreamUtilsLocation PhotoStreamUtilsLocation;
typedef struct _PhotoStreamUtilsLocationClass PhotoStreamUtilsLocationClass;

#define PHOTO_STREAM_UTILS_TYPE_USER (photo_stream_utils_user_get_type ())
#define PHOTO_STREAM_UTILS_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_USER, PhotoStreamUtilsUser))
#define PHOTO_STREAM_UTILS_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_USER, PhotoStreamUtilsUserClass))
#define PHOTO_STREAM_UTILS_IS_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_USER))
#define PHOTO_STREAM_UTILS_IS_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_USER))
#define PHOTO_STREAM_UTILS_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_USER, PhotoStreamUtilsUserClass))

typedef struct _PhotoStreamUtilsUser PhotoStreamUtilsUser;
typedef struct _PhotoStreamUtilsUserClass PhotoStreamUtilsUserClass;

#define PHOTO_STREAM_UTILS_TYPE_MEDIA (photo_stream_utils_media_get_type ())
#define PHOTO_STREAM_UTILS_MEDIA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA, PhotoStreamUtilsMedia))
#define PHOTO_STREAM_UTILS_MEDIA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_MEDIA, PhotoStreamUtilsMediaClass))
#define PHOTO_STREAM_UTILS_IS_MEDIA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA))
#define PHOTO_STREAM_UTILS_IS_MEDIA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_MEDIA))
#define PHOTO_STREAM_UTILS_MEDIA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_MEDIA, PhotoStreamUtilsMediaClass))

typedef struct _PhotoStreamUtilsMedia PhotoStreamUtilsMedia;
typedef struct _PhotoStreamUtilsMediaClass PhotoStreamUtilsMediaClass;

#define PHOTO_STREAM_UTILS_TYPE_TAGGED_USER (photo_stream_utils_tagged_user_get_type ())
#define PHOTO_STREAM_UTILS_TAGGED_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_UTILS_TYPE_TAGGED_USER, PhotoStreamUtilsTaggedUser))
#define PHOTO_STREAM_UTILS_TAGGED_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_UTILS_TYPE_TAGGED_USER, PhotoStreamUtilsTaggedUserClass))
#define PHOTO_STREAM_UTILS_IS_TAGGED_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_UTILS_TYPE_TAGGED_USER))
#define PHOTO_STREAM_UTILS_IS_TAGGED_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_UTILS_TYPE_TAGGED_USER))
#define PHOTO_STREAM_UTILS_TAGGED_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_UTILS_TYPE_TAGGED_USER, PhotoStreamUtilsTaggedUserClass))

typedef struct _PhotoStreamUtilsTaggedUser PhotoStreamUtilsTaggedUser;
typedef struct _PhotoStreamUtilsTaggedUserClass PhotoStreamUtilsTaggedUserClass;
typedef struct _Block24Data Block24Data;

#define PHOTO_STREAM_TYPE_APP (photo_stream_app_get_type ())
#define PHOTO_STREAM_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PHOTO_STREAM_TYPE_APP, PhotoStreamApp))
#define PHOTO_STREAM_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PHOTO_STREAM_TYPE_APP, PhotoStreamAppClass))
#define PHOTO_STREAM_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PHOTO_STREAM_TYPE_APP))
#define PHOTO_STREAM_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PHOTO_STREAM_TYPE_APP))
#define PHOTO_STREAM_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PHOTO_STREAM_TYPE_APP, PhotoStreamAppClass))

typedef struct _PhotoStreamApp PhotoStreamApp;
typedef struct _PhotoStreamAppClass PhotoStreamAppClass;
#define _photo_stream_utils_media_info_unref0(var) ((var == NULL) ? NULL : (var = (photo_stream_utils_media_info_unref (var), NULL)))
typedef struct _Block25Data Block25Data;
typedef struct _PhotoStreamUtilsMediaPrivate PhotoStreamUtilsMediaPrivate;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _PhotoStreamWidgetsPostList {
	GtkBox parent_instance;
	PhotoStreamWidgetsPostListPrivate * priv;
	GList* boxes;
	GList* srcImages;
	GtkButton* moreButton;
	GtkAlignment* moreButtonAlignment;
	GtkButton* moreButtonImages;
	GtkAlignment* moreButtonImagesAlignment;
	gchar* olderFeedLink;
	gint IMAGE_SIZE;
	GtkScrolledWindow* postsWindow;
	GtkScrolledWindow* imagesWindow;
	GtkStack* stack;
	GtkListBox* postList;
	GtkBox* imagesBox;
	GtkGrid* imagesGrid;
};

struct _PhotoStreamWidgetsPostListClass {
	GtkBoxClass parent_class;
};

struct _PhotoStreamWidgetsPostListPrivate {
	GtkWindow* parentWindow;
	gint prevWidth;
	gboolean cannotViewImages;
};

struct _PhotoStreamWidgetsPostBox {
	GtkEventBox parent_instance;
	PhotoStreamWidgetsPostBoxPrivate * priv;
	GtkBox* box;
	GtkAlignment* avatarAlignment;
	GtkAlignment* userNameAlignment;
	GtkAlignment* dateAlignment;
	GtkAlignment* imageAlignment;
	GtkAlignment* titleAlignment;
	GtkAlignment* locationAlignment;
	GtkAlignment* likeAlignment;
	GtkAlignment* commentsAlignment;
	GdkPixbuf* likePixbuf;
	GdkPixbuf* dislikePixbuf;
	GtkBox* userToolbar;
	GtkLabel* userNameLabel;
	PhotoStreamWidgetsDateLabel* dateLabel;
	GtkLabel* titleLabel;
	GtkLabel* likesLabel;
	GtkImage* avatar;
	GtkEventBox* avatarBox;
	GtkEventBox* imageEventBox;
	GtkFixed* imageBox;
	GtkImage* image;
	GtkBox* likeToolbar;
	GtkEventBox* likeBox;
	GList* usersOnPhoto;
	GtkImage* likeImage;
	GtkEventBox* locationEventBox;
	GtkBox* locationBox;
	GtkImage* locationImage;
	GtkLabel* locationLabel;
	GdkPixbuf* locationPixbuf;
	gchar* likesText;
	gboolean windowOpened;
	PhotoStreamWidgetsCommentsList* commentList;
	PhotoStreamUtilsMediaInfo* post;
};

struct _PhotoStreamWidgetsPostBoxClass {
	GtkEventBoxClass parent_class;
};

struct _PhotoStreamUtilsMediaInfo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsMediaInfoPrivate * priv;
	gint type;
	GList* tags;
	gint64 commentsCount;
	GList* comments;
	gchar* filter;
	GDateTime* creationTime;
	PhotoStreamUtilsLocation* location;
	gchar* link;
	GList* likes;
	gint64 likesCount;
	PhotoStreamUtilsMedia* media;
	GList* taggedUsers;
	gchar* title;
	PhotoStreamUtilsUser* postedUser;
	gchar* id;
	gboolean didILikeThis;
};

struct _PhotoStreamUtilsMediaInfoClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsMediaInfo *self);
};

struct _Block24Data {
	int _ref_count_;
	PhotoStreamWidgetsPostList* self;
	PhotoStreamWidgetsPostBox* box;
};

struct _Block25Data {
	int _ref_count_;
	Block24Data * _data24_;
	PhotoStreamApp* app;
	PhotoStreamUtilsMediaInfo* post;
};

struct _PhotoStreamUtilsMedia {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PhotoStreamUtilsMediaPrivate * priv;
	gchar* url;
	gint64 width;
	gint64 height;
	gchar* previewUrl;
};

struct _PhotoStreamUtilsMediaClass {
	GTypeClass parent_class;
	void (*finalize) (PhotoStreamUtilsMedia *self);
};


static gpointer photo_stream_widgets_post_list_parent_class = NULL;
extern gchar* photo_stream_app_CACHE_URL;

GType photo_stream_widgets_post_list_get_type (void) G_GNUC_CONST;
GType photo_stream_widgets_post_box_get_type (void) G_GNUC_CONST;
#define PHOTO_STREAM_WIDGETS_POST_LIST_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), PHOTO_STREAM_WIDGETS_TYPE_POST_LIST, PhotoStreamWidgetsPostListPrivate))
enum  {
	PHOTO_STREAM_WIDGETS_POST_LIST_DUMMY_PROPERTY
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
PhotoStreamWidgetsPostList* photo_stream_widgets_post_list_new (gboolean cannotViewImages);
PhotoStreamWidgetsPostList* photo_stream_widgets_post_list_construct (GType object_type, gboolean cannotViewImages);
gboolean loadPostsOrImages (void);
void photo_stream_widgets_post_list_deleteMoreButton (PhotoStreamWidgetsPostList* self);
gpointer photo_stream_utils_media_info_ref (gpointer instance);
void photo_stream_utils_media_info_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_media_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_media_info (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_media_info (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_media_info (const GValue* value);
GType photo_stream_utils_media_info_get_type (void) G_GNUC_CONST;
gboolean photo_stream_widgets_post_list_contains (PhotoStreamWidgetsPostList* self, PhotoStreamUtilsMediaInfo* post);
GType photo_stream_widgets_date_label_get_type (void) G_GNUC_CONST;
GType photo_stream_widgets_comments_list_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_comment_ref (gpointer instance);
void photo_stream_utils_comment_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_comment (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_comment (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_comment (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_comment (const GValue* value);
GType photo_stream_utils_comment_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_location_ref (gpointer instance);
void photo_stream_utils_location_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_location (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_location (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_location (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_location (const GValue* value);
GType photo_stream_utils_location_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_user_ref (gpointer instance);
void photo_stream_utils_user_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_user (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_user (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_user (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_user (const GValue* value);
GType photo_stream_utils_user_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_media_ref (gpointer instance);
void photo_stream_utils_media_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_media (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_media (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_media (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_media (const GValue* value);
GType photo_stream_utils_media_get_type (void) G_GNUC_CONST;
gpointer photo_stream_utils_tagged_user_ref (gpointer instance);
void photo_stream_utils_tagged_user_unref (gpointer instance);
GParamSpec* photo_stream_utils_param_spec_tagged_user (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void photo_stream_utils_value_set_tagged_user (GValue* value, gpointer v_object);
void photo_stream_utils_value_take_tagged_user (GValue* value, gpointer v_object);
gpointer photo_stream_utils_value_get_tagged_user (const GValue* value);
GType photo_stream_utils_tagged_user_get_type (void) G_GNUC_CONST;
void photo_stream_widgets_post_list_append (PhotoStreamWidgetsPostList* self, PhotoStreamUtilsMediaInfo* post);
PhotoStreamWidgetsPostBox* photo_stream_widgets_post_box_new (PhotoStreamUtilsMediaInfo* post);
PhotoStreamWidgetsPostBox* photo_stream_widgets_post_box_construct (GType object_type, PhotoStreamUtilsMediaInfo* post);
void photo_stream_widgets_post_list_prepend (PhotoStreamWidgetsPostList* self, PhotoStreamUtilsMediaInfo* post);
static Block24Data* block24_data_ref (Block24Data* _data24_);
static void block24_data_unref (void * _userdata_);
static void ___lambda39_ (Block24Data* _data24_, PhotoStreamUtilsMediaInfo* post);
GType photo_stream_app_get_type (void) G_GNUC_CONST;
static Block25Data* block25_data_ref (Block25Data* _data25_);
static void block25_data_unref (void * _userdata_);
#define PHOTO_STREAM_MEDIA_TYPE_VIDEO 2
gchar* getFileName (const gchar* url);
static gboolean __lambda40_ (PhotoStreamWidgetsPostList* self, GdkEventCrossing* event);
static gboolean ___lambda40__gtk_widget_enter_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self);
static gboolean __lambda41_ (Block25Data* _data25_, GdkEventButton* event);
gint photo_stream_app_loadPost (PhotoStreamApp* self, const gchar* id);
static gboolean ___lambda41__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static void photo_stream_widgets_post_list_loadImageToFeed (PhotoStreamWidgetsPostList* self, gint index, gboolean isVideo);
static void ____lambda39__photo_stream_widgets_post_box_image_loaded (PhotoStreamWidgetsPostBox* _sender, PhotoStreamUtilsMediaInfo* post, gpointer self);
void photo_stream_widgets_post_list_resizeAllImages (PhotoStreamWidgetsPostList* self, gint windowSize);
#define PHOTO_STREAM_APP_CACHE_IMAGES "/usr/share/photostream/images/"
void photo_stream_widgets_post_list_clear (PhotoStreamWidgetsPostList* self);
static void photo_stream_widgets_post_list_finalize (GObject* obj);


static void _g_object_unref0_ (gpointer var) {
#line 7 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 356 "PostList.c"
}


static void _g_list_free__g_object_unref0_ (GList* self) {
#line 7 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 7 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_list_free (self);
#line 365 "PostList.c"
}


PhotoStreamWidgetsPostList* photo_stream_widgets_post_list_construct (GType object_type, gboolean cannotViewImages) {
	PhotoStreamWidgetsPostList * self = NULL;
	gboolean _tmp0_ = FALSE;
	GtkStack* _tmp1_ = NULL;
	GtkListBox* _tmp2_ = NULL;
	GtkButton* _tmp3_ = NULL;
	GtkAlignment* _tmp4_ = NULL;
	GtkAlignment* _tmp5_ = NULL;
	GtkButton* _tmp6_ = NULL;
	GtkListBox* _tmp7_ = NULL;
	GtkAlignment* _tmp8_ = NULL;
	GtkButton* _tmp9_ = NULL;
	GtkAlignment* _tmp10_ = NULL;
	GtkAlignment* _tmp11_ = NULL;
	GtkButton* _tmp12_ = NULL;
	GtkListBox* _tmp13_ = NULL;
	GtkListBox* _tmp14_ = NULL;
	GtkBox* _tmp15_ = NULL;
	GtkGrid* _tmp16_ = NULL;
	GtkGrid* _tmp17_ = NULL;
	GtkGrid* _tmp18_ = NULL;
	GtkBox* _tmp19_ = NULL;
	GtkGrid* _tmp20_ = NULL;
	GtkBox* _tmp21_ = NULL;
	GtkAlignment* _tmp22_ = NULL;
	GtkScrolledWindow* _tmp23_ = NULL;
	GtkScrolledWindow* _tmp24_ = NULL;
	GtkScrolledWindow* _tmp25_ = NULL;
	GtkListBox* _tmp26_ = NULL;
	GtkScrolledWindow* _tmp27_ = NULL;
	GtkScrolledWindow* _tmp28_ = NULL;
	GtkScrolledWindow* _tmp29_ = NULL;
	GtkBox* _tmp30_ = NULL;
	GtkStack* _tmp31_ = NULL;
	GtkScrolledWindow* _tmp32_ = NULL;
	gboolean _tmp33_ = FALSE;
	GtkStack* _tmp38_ = NULL;
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self = (PhotoStreamWidgetsPostList*) g_object_new (object_type, NULL);
#line 30 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp0_ = cannotViewImages;
#line 30 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->priv->cannotViewImages = _tmp0_;
#line 31 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_VERTICAL);
#line 32 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->IMAGE_SIZE = 200;
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp1_ = (GtkStack*) gtk_stack_new ();
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp1_);
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->stack);
#line 34 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->stack = _tmp1_;
#line 35 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp2_ = (GtkListBox*) gtk_list_box_new ();
#line 35 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp2_);
#line 35 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->postList);
#line 35 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->postList = _tmp2_;
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	__g_list_free__g_object_unref0_0 (self->boxes);
#line 37 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->boxes = NULL;
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	__g_list_free__g_object_unref0_0 (self->srcImages);
#line 38 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->srcImages = NULL;
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp3_ = (GtkButton*) gtk_button_new_with_label ("Load more...");
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp3_);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->moreButton);
#line 40 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->moreButton = _tmp3_;
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp4_ = (GtkAlignment*) gtk_alignment_new ((gfloat) 1, (gfloat) 0, (gfloat) 1, (gfloat) 0);
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp4_);
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->moreButtonAlignment);
#line 42 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->moreButtonAlignment = _tmp4_;
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp5_ = self->moreButtonAlignment;
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp6_ = self->moreButton;
#line 43 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_container_add ((GtkContainer*) _tmp5_, (GtkWidget*) _tmp6_);
#line 44 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp7_ = self->postList;
#line 44 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp8_ = self->moreButtonAlignment;
#line 44 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_list_box_prepend (_tmp7_, (GtkWidget*) _tmp8_);
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp9_ = (GtkButton*) gtk_button_new_with_label ("Load more...");
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp9_);
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->moreButtonImages);
#line 46 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->moreButtonImages = _tmp9_;
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp10_ = (GtkAlignment*) gtk_alignment_new ((gfloat) 1, (gfloat) 0, (gfloat) 1, (gfloat) 0);
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp10_);
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->moreButtonImagesAlignment);
#line 48 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->moreButtonImagesAlignment = _tmp10_;
#line 49 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp11_ = self->moreButtonImagesAlignment;
#line 49 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp12_ = self->moreButtonImages;
#line 49 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_container_add ((GtkContainer*) _tmp11_, (GtkWidget*) _tmp12_);
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp13_ = self->postList;
#line 51 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_list_box_set_selection_mode (_tmp13_, GTK_SELECTION_NONE);
#line 52 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp14_ = self->postList;
#line 52 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_list_box_set_activate_on_single_click (_tmp14_, FALSE);
#line 54 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp15_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 54 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp15_);
#line 54 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->imagesBox);
#line 54 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->imagesBox = _tmp15_;
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp16_ = (GtkGrid*) gtk_grid_new ();
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp16_);
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->imagesGrid);
#line 55 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->imagesGrid = _tmp16_;
#line 56 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp17_ = self->imagesGrid;
#line 56 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_grid_set_row_spacing (_tmp17_, (guint) 5);
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp18_ = self->imagesGrid;
#line 57 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_grid_set_column_spacing (_tmp18_, (guint) 5);
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp19_ = self->imagesBox;
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp20_ = self->imagesGrid;
#line 58 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_container_add ((GtkContainer*) _tmp19_, (GtkWidget*) _tmp20_);
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp21_ = self->imagesBox;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp22_ = self->moreButtonImagesAlignment;
#line 59 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_box_pack_end (_tmp21_, (GtkWidget*) _tmp22_, FALSE, FALSE, (guint) 0);
#line 61 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp23_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 61 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp23_);
#line 61 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->postsWindow);
#line 61 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->postsWindow = _tmp23_;
#line 62 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp24_ = self->postsWindow;
#line 62 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_scrolled_window_set_policy (_tmp24_, GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
#line 63 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp25_ = self->postsWindow;
#line 63 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp26_ = self->postList;
#line 63 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_scrolled_window_add_with_viewport (_tmp25_, (GtkWidget*) _tmp26_);
#line 65 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp27_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 65 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp27_);
#line 65 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->imagesWindow);
#line 65 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->imagesWindow = _tmp27_;
#line 66 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp28_ = self->imagesWindow;
#line 66 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_scrolled_window_set_policy (_tmp28_, GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
#line 67 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp29_ = self->imagesWindow;
#line 67 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp30_ = self->imagesBox;
#line 67 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_scrolled_window_add_with_viewport (_tmp29_, (GtkWidget*) _tmp30_);
#line 68 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp31_ = self->stack;
#line 68 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp32_ = self->postsWindow;
#line 68 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_stack_add_named (_tmp31_, (GtkWidget*) _tmp32_, "posts");
#line 69 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp33_ = cannotViewImages;
#line 69 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (!_tmp33_) {
#line 580 "PostList.c"
		GtkStack* _tmp34_ = NULL;
		GtkScrolledWindow* _tmp35_ = NULL;
		gboolean _tmp36_ = FALSE;
#line 71 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp34_ = self->stack;
#line 71 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp35_ = self->imagesWindow;
#line 71 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		gtk_stack_add_named (_tmp34_, (GtkWidget*) _tmp35_, "images");
#line 72 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp36_ = loadPostsOrImages ();
#line 72 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		if (_tmp36_) {
#line 594 "PostList.c"
			GtkStack* _tmp37_ = NULL;
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp37_ = self->stack;
#line 73 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			gtk_stack_set_visible_child_name (_tmp37_, "images");
#line 600 "PostList.c"
		}
	}
#line 75 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp38_ = self->stack;
#line 75 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp38_, TRUE, TRUE, (guint) 0);
#line 76 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return self;
#line 611 "PostList.c"
}


PhotoStreamWidgetsPostList* photo_stream_widgets_post_list_new (gboolean cannotViewImages) {
#line 28 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return photo_stream_widgets_post_list_construct (PHOTO_STREAM_WIDGETS_TYPE_POST_LIST, cannotViewImages);
#line 618 "PostList.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return self ? g_object_ref (self) : NULL;
#line 625 "PostList.c"
}


void photo_stream_widgets_post_list_deleteMoreButton (PhotoStreamWidgetsPostList* self) {
	GtkAlignment* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
#line 79 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_if_fail (self != NULL);
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp0_ = self->moreButtonAlignment;
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp1_ = self->postList;
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp2_ = gtk_widget_is_ancestor ((GtkWidget*) _tmp0_, (GtkWidget*) _tmp1_);
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (_tmp2_) {
#line 643 "PostList.c"
		GtkListBoxRow* buttonRow = NULL;
		GtkListBox* _tmp3_ = NULL;
		GList* _tmp4_ = NULL;
		GList* _tmp5_ = NULL;
		GList* _tmp6_ = NULL;
		gconstpointer _tmp7_ = NULL;
		GtkListBoxRow* _tmp8_ = NULL;
		GtkListBoxRow* _tmp9_ = NULL;
		GtkListBoxRow* _tmp10_ = NULL;
		GtkAlignment* _tmp11_ = NULL;
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp3_ = self->postList;
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp4_ = gtk_container_get_children ((GtkContainer*) _tmp3_);
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp5_ = _tmp4_;
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp6_ = g_list_last (_tmp5_);
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp7_ = _tmp6_->data;
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp8_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST ((GtkWidget*) _tmp7_, gtk_list_box_row_get_type (), GtkListBoxRow));
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp9_ = _tmp8_;
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_list_free0 (_tmp5_);
#line 83 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		buttonRow = _tmp9_;
#line 84 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp10_ = buttonRow;
#line 84 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp11_ = self->moreButtonAlignment;
#line 84 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		gtk_container_remove ((GtkContainer*) _tmp10_, (GtkWidget*) _tmp11_);
#line 81 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_object_unref0 (buttonRow);
#line 680 "PostList.c"
	}
}


gboolean photo_stream_widgets_post_list_contains (PhotoStreamWidgetsPostList* self, PhotoStreamUtilsMediaInfo* post) {
	gboolean result = FALSE;
	GList* _tmp0_ = NULL;
#line 87 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 87 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_val_if_fail (post != NULL, FALSE);
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp0_ = self->boxes;
#line 694 "PostList.c"
	{
		GList* box_collection = NULL;
		GList* box_it = NULL;
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		box_collection = _tmp0_;
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		for (box_it = box_collection; box_it != NULL; box_it = box_it->next) {
#line 702 "PostList.c"
			PhotoStreamWidgetsPostBox* _tmp1_ = NULL;
			PhotoStreamWidgetsPostBox* box = NULL;
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp1_ = _g_object_ref0 ((PhotoStreamWidgetsPostBox*) box_it->data);
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			box = _tmp1_;
#line 709 "PostList.c"
			{
				PhotoStreamWidgetsPostBox* _tmp2_ = NULL;
				PhotoStreamUtilsMediaInfo* _tmp3_ = NULL;
				const gchar* _tmp4_ = NULL;
				PhotoStreamUtilsMediaInfo* _tmp5_ = NULL;
				const gchar* _tmp6_ = NULL;
#line 90 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp2_ = box;
#line 90 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp3_ = _tmp2_->post;
#line 90 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp4_ = _tmp3_->id;
#line 90 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp5_ = post;
#line 90 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp6_ = _tmp5_->id;
#line 90 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				if (g_strcmp0 (_tmp4_, _tmp6_) == 0) {
#line 91 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
					result = TRUE;
#line 91 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
					_g_object_unref0 (box);
#line 91 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
					return result;
#line 734 "PostList.c"
				}
#line 89 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_g_object_unref0 (box);
#line 738 "PostList.c"
			}
		}
	}
#line 93 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	result = FALSE;
#line 93 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return result;
#line 746 "PostList.c"
}


void photo_stream_widgets_post_list_append (PhotoStreamWidgetsPostList* self, PhotoStreamUtilsMediaInfo* post) {
	GtkSeparator* separator = NULL;
	GtkSeparator* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	PhotoStreamWidgetsPostBox* box = NULL;
	PhotoStreamUtilsMediaInfo* _tmp2_ = NULL;
	PhotoStreamWidgetsPostBox* _tmp3_ = NULL;
	GtkListBoxRow* listBoxRow = NULL;
	GtkListBoxRow* _tmp4_ = NULL;
	GtkListBox* _tmp5_ = NULL;
	PhotoStreamWidgetsPostBox* _tmp6_ = NULL;
#line 95 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_if_fail (self != NULL);
#line 95 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_if_fail (post != NULL);
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp0_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp0_);
#line 97 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	separator = _tmp0_;
#line 98 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp1_ = self->postList;
#line 98 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_list_box_prepend (_tmp1_, (GtkWidget*) separator);
#line 99 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp2_ = post;
#line 99 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp3_ = photo_stream_widgets_post_box_new (_tmp2_);
#line 99 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp3_);
#line 99 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	box = _tmp3_;
#line 101 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp4_ = (GtkListBoxRow*) gtk_list_box_row_new ();
#line 101 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp4_);
#line 101 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	listBoxRow = _tmp4_;
#line 103 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_container_add ((GtkContainer*) listBoxRow, (GtkWidget*) box);
#line 104 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp5_ = self->postList;
#line 104 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_list_box_prepend (_tmp5_, (GtkWidget*) listBoxRow);
#line 105 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp6_ = _g_object_ref0 (box);
#line 105 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->boxes = g_list_prepend (self->boxes, _tmp6_);
#line 95 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (listBoxRow);
#line 95 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (box);
#line 95 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (separator);
#line 805 "PostList.c"
}


static Block24Data* block24_data_ref (Block24Data* _data24_) {
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_atomic_int_inc (&_data24_->_ref_count_);
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return _data24_;
#line 814 "PostList.c"
}


static void block24_data_unref (void * _userdata_) {
	Block24Data* _data24_;
	_data24_ = (Block24Data*) _userdata_;
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (g_atomic_int_dec_and_test (&_data24_->_ref_count_)) {
#line 823 "PostList.c"
		PhotoStreamWidgetsPostList* self;
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		self = _data24_->self;
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_object_unref0 (_data24_->box);
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_object_unref0 (self);
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		g_slice_free (Block24Data, _data24_);
#line 833 "PostList.c"
	}
}


static gpointer _photo_stream_utils_media_info_ref0 (gpointer self) {
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return self ? photo_stream_utils_media_info_ref (self) : NULL;
#line 841 "PostList.c"
}


static Block25Data* block25_data_ref (Block25Data* _data25_) {
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_atomic_int_inc (&_data25_->_ref_count_);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return _data25_;
#line 850 "PostList.c"
}


static void block25_data_unref (void * _userdata_) {
	Block25Data* _data25_;
	_data25_ = (Block25Data*) _userdata_;
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (g_atomic_int_dec_and_test (&_data25_->_ref_count_)) {
#line 859 "PostList.c"
		PhotoStreamWidgetsPostList* self;
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		self = _data25_->_data24_->self;
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_object_unref0 (_data25_->app);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_photo_stream_utils_media_info_unref0 (_data25_->post);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		block24_data_unref (_data25_->_data24_);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_data25_->_data24_ = NULL;
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		g_slice_free (Block25Data, _data25_);
#line 873 "PostList.c"
	}
}


static gboolean __lambda40_ (PhotoStreamWidgetsPostList* self, GdkEventCrossing* event) {
	gboolean result = FALSE;
	GdkEventCrossing* _tmp0_ = NULL;
	GdkWindow* _tmp1_ = NULL;
	GdkDisplay* _tmp2_ = NULL;
	GdkCursor* _tmp3_ = NULL;
	GdkCursor* _tmp4_ = NULL;
#line 152 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 153 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp0_ = event;
#line 153 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp1_ = _tmp0_->window;
#line 153 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp2_ = gdk_display_get_default ();
#line 153 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp3_ = gdk_cursor_new_from_name (_tmp2_, "hand2");
#line 153 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp4_ = _tmp3_;
#line 153 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gdk_window_set_cursor (_tmp1_, _tmp4_);
#line 153 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (_tmp4_);
#line 156 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	result = FALSE;
#line 156 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return result;
#line 905 "PostList.c"
}


static gboolean ___lambda40__gtk_widget_enter_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self) {
	gboolean result;
	result = __lambda40_ ((PhotoStreamWidgetsPostList*) self, event);
#line 152 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return result;
#line 914 "PostList.c"
}


static gboolean __lambda41_ (Block25Data* _data25_, GdkEventButton* event) {
	Block24Data* _data24_;
	PhotoStreamWidgetsPostList* self;
	gboolean result = FALSE;
	PhotoStreamApp* _tmp0_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
#line 159 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data24_ = _data25_->_data24_;
#line 159 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self = _data24_->self;
#line 159 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 160 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp0_ = _data25_->app;
#line 160 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp1_ = _data25_->post;
#line 160 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp2_ = _tmp1_->id;
#line 160 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	photo_stream_app_loadPost (_tmp0_, _tmp2_);
#line 161 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	result = FALSE;
#line 161 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return result;
#line 943 "PostList.c"
}


static gboolean ___lambda41__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda41_ (self, event);
#line 159 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	return result;
#line 952 "PostList.c"
}


static void ___lambda39_ (Block24Data* _data24_, PhotoStreamUtilsMediaInfo* post) {
	PhotoStreamWidgetsPostList* self;
	Block25Data* _data25_;
	PhotoStreamUtilsMediaInfo* _tmp0_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gchar* imageFileName = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gint index = 0;
	GList* _tmp16_ = NULL;
	PhotoStreamWidgetsPostBox* _tmp17_ = NULL;
	gint _tmp18_ = 0;
	GtkEventBox* tmpEventBox = NULL;
	GtkEventBox* _tmp22_ = NULL;
	GtkImage* tmpImage = NULL;
	GtkImage* _tmp23_ = NULL;
	GtkEventBox* _tmp24_ = NULL;
	GtkImage* _tmp25_ = NULL;
	GtkEventBox* _tmp26_ = NULL;
	GtkEventBox* _tmp27_ = NULL;
	GtkEventBox* _tmp28_ = NULL;
	GtkWidget* toplevel = NULL;
	GtkWidget* _tmp29_ = NULL;
	GtkWidget* _tmp30_ = NULL;
	GtkWidget* _tmp31_ = NULL;
	GtkWindow* _tmp32_ = NULL;
	GtkWindow* _tmp33_ = NULL;
	GtkWindow* _tmp34_ = NULL;
	gint _tmp35_ = 0;
	GtkWindow* _tmp36_ = NULL;
	GtkApplication* _tmp37_ = NULL;
	PhotoStreamApp* _tmp38_ = NULL;
	GtkEventBox* _tmp39_ = NULL;
	GtkEventBox* _tmp40_ = NULL;
	GtkGrid* _tmp41_ = NULL;
	GtkEventBox* _tmp42_ = NULL;
	PhotoStreamWidgetsPostBox* _tmp43_ = NULL;
	PhotoStreamUtilsMediaInfo* _tmp44_ = NULL;
	gint _tmp45_ = 0;
	gboolean _tmp46_ = FALSE;
	GError * _inner_error_ = NULL;
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self = _data24_->self;
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_if_fail (post != NULL);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data25_ = g_slice_new0 (Block25Data);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data25_->_ref_count_ = 1;
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data25_->_data24_ = block24_data_ref (_data24_);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp0_ = post;
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp1_ = _photo_stream_utils_media_info_ref0 (_tmp0_);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_photo_stream_utils_media_info_unref0 (_data25_->post);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data25_->post = _tmp1_;
#line 123 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp3_ = _data25_->post;
#line 123 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp4_ = _tmp3_->type;
#line 123 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (_tmp4_ == PHOTO_STREAM_MEDIA_TYPE_VIDEO) {
#line 1027 "PostList.c"
		PhotoStreamUtilsMediaInfo* _tmp5_ = NULL;
		PhotoStreamUtilsMedia* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
#line 124 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp5_ = _data25_->post;
#line 124 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp6_ = _tmp5_->media;
#line 124 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp7_ = _tmp6_->previewUrl;
#line 124 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp2_ = _tmp7_;
#line 1039 "PostList.c"
	} else {
		PhotoStreamUtilsMediaInfo* _tmp8_ = NULL;
		PhotoStreamUtilsMedia* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
#line 125 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp8_ = _data25_->post;
#line 125 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp9_ = _tmp8_->media;
#line 125 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp10_ = _tmp9_->url;
#line 125 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp2_ = _tmp10_;
#line 1052 "PostList.c"
	}
#line 123 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp11_ = photo_stream_app_CACHE_URL;
#line 123 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp12_ = getFileName (_tmp2_);
#line 123 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp13_ = _tmp12_;
#line 123 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp14_ = g_strconcat (_tmp11_, _tmp13_, NULL);
#line 123 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp15_ = _tmp14_;
#line 123 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_free0 (_tmp13_);
#line 123 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	imageFileName = _tmp15_;
#line 126 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp16_ = self->boxes;
#line 126 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp17_ = _data24_->box;
#line 126 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp18_ = g_list_index (_tmp16_, _tmp17_);
#line 126 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	index = _tmp18_;
#line 1076 "PostList.c"
	{
		GdkPixbuf* _tmp19_ = NULL;
		GdkPixbuf* _tmp20_ = NULL;
		GdkPixbuf* _tmp21_ = NULL;
#line 130 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp20_ = gdk_pixbuf_new_from_file (imageFileName, &_inner_error_);
#line 130 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp19_ = _tmp20_;
#line 130 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1087 "PostList.c"
			goto __catch30_g_error;
		}
#line 130 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp21_ = _tmp19_;
#line 130 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp19_ = NULL;
#line 130 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		self->srcImages = g_list_append (self->srcImages, _tmp21_);
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_object_unref0 (_tmp19_);
#line 1098 "PostList.c"
	}
	goto __finally30;
	__catch30_g_error:
	{
		GError* e = NULL;
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		e = _inner_error_;
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_inner_error_ = NULL;
#line 134 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		g_error ("PostList.vala:134: Something wrong with file loading.\n");
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_error_free0 (e);
#line 1112 "PostList.c"
	}
	__finally30:
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_free0 (imageFileName);
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		block25_data_unref (_data25_);
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_data25_ = NULL;
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		g_clear_error (&_inner_error_);
#line 128 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		return;
#line 1129 "PostList.c"
	}
#line 137 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp22_ = (GtkEventBox*) gtk_event_box_new ();
#line 137 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp22_);
#line 137 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	tmpEventBox = _tmp22_;
#line 138 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp23_ = (GtkImage*) gtk_image_new ();
#line 138 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp23_);
#line 138 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	tmpImage = _tmp23_;
#line 139 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp24_ = tmpEventBox;
#line 139 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp25_ = tmpImage;
#line 139 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_container_add ((GtkContainer*) _tmp24_, (GtkWidget*) _tmp25_);
#line 141 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp26_ = tmpEventBox;
#line 141 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_widget_set_events ((GtkWidget*) _tmp26_, (gint) GDK_BUTTON_RELEASE_MASK);
#line 142 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp27_ = tmpEventBox;
#line 142 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_widget_set_events ((GtkWidget*) _tmp27_, (gint) GDK_ENTER_NOTIFY_MASK);
#line 143 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp28_ = tmpEventBox;
#line 143 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_widget_set_events ((GtkWidget*) _tmp28_, (gint) GDK_LEAVE_NOTIFY_MASK);
#line 145 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp29_ = gtk_widget_get_toplevel ((GtkWidget*) self);
#line 145 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp30_ = _g_object_ref0 (_tmp29_);
#line 145 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	toplevel = _tmp30_;
#line 146 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp31_ = toplevel;
#line 146 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp32_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp31_, gtk_window_get_type (), GtkWindow));
#line 146 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->priv->parentWindow);
#line 146 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->priv->parentWindow = _tmp32_;
#line 147 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp33_ = self->priv->parentWindow;
#line 147 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_widget_add_events ((GtkWidget*) _tmp33_, (gint) GDK_CONFIGURE);
#line 148 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp34_ = self->priv->parentWindow;
#line 148 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp35_ = gtk_widget_get_allocated_width ((GtkWidget*) _tmp34_);
#line 148 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->priv->prevWidth = _tmp35_;
#line 150 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp36_ = self->priv->parentWindow;
#line 150 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp37_ = gtk_window_get_application (_tmp36_);
#line 150 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp38_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp37_, PHOTO_STREAM_TYPE_APP, PhotoStreamApp));
#line 150 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data25_->app = _tmp38_;
#line 152 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp39_ = tmpEventBox;
#line 152 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_signal_connect_object ((GtkWidget*) _tmp39_, "enter-notify-event", (GCallback) ___lambda40__gtk_widget_enter_notify_event, self, 0);
#line 159 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp40_ = tmpEventBox;
#line 159 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_signal_connect_data ((GtkWidget*) _tmp40_, "button-release-event", (GCallback) ___lambda41__gtk_widget_button_release_event, block25_data_ref (_data25_), (GClosureNotify) block25_data_unref, 0);
#line 173 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp41_ = self->imagesGrid;
#line 173 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp42_ = tmpEventBox;
#line 173 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_grid_attach (_tmp41_, (GtkWidget*) _tmp42_, index % 3, index / 3, 1, 1);
#line 175 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp43_ = _data24_->box;
#line 175 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp44_ = _tmp43_->post;
#line 175 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp45_ = _tmp44_->type;
#line 175 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	photo_stream_widgets_post_list_loadImageToFeed (self, index, _tmp45_ == PHOTO_STREAM_MEDIA_TYPE_VIDEO);
#line 176 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp46_ = loadPostsOrImages ();
#line 176 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (_tmp46_) {
#line 1219 "PostList.c"
		GtkStack* _tmp47_ = NULL;
#line 177 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp47_ = self->stack;
#line 177 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		gtk_stack_set_visible_child_name (_tmp47_, "images");
#line 1225 "PostList.c"
	}
#line 178 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (toplevel);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (tmpImage);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (tmpEventBox);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_free0 (imageFileName);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	block25_data_unref (_data25_);
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data25_ = NULL;
#line 1241 "PostList.c"
}


static void ____lambda39__photo_stream_widgets_post_box_image_loaded (PhotoStreamWidgetsPostBox* _sender, PhotoStreamUtilsMediaInfo* post, gpointer self) {
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	___lambda39_ (self, post);
#line 1248 "PostList.c"
}


void photo_stream_widgets_post_list_prepend (PhotoStreamWidgetsPostList* self, PhotoStreamUtilsMediaInfo* post) {
	Block24Data* _data24_;
	GtkSeparator* separator = NULL;
	GtkSeparator* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	GtkSeparator* _tmp2_ = NULL;
	GtkListBox* _tmp3_ = NULL;
	GList* _tmp4_ = NULL;
	GList* _tmp5_ = NULL;
	guint _tmp6_ = 0U;
	PhotoStreamUtilsMediaInfo* _tmp7_ = NULL;
	PhotoStreamWidgetsPostBox* _tmp8_ = NULL;
	GtkListBoxRow* listBoxRow = NULL;
	GtkListBoxRow* _tmp9_ = NULL;
	GtkListBoxRow* _tmp10_ = NULL;
	PhotoStreamWidgetsPostBox* _tmp11_ = NULL;
	GtkListBox* _tmp12_ = NULL;
	GtkListBoxRow* _tmp13_ = NULL;
	GtkListBox* _tmp14_ = NULL;
	GList* _tmp15_ = NULL;
	GList* _tmp16_ = NULL;
	guint _tmp17_ = 0U;
	PhotoStreamWidgetsPostBox* _tmp18_ = NULL;
	PhotoStreamWidgetsPostBox* _tmp19_ = NULL;
	gboolean _tmp20_ = FALSE;
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_if_fail (self != NULL);
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_if_fail (post != NULL);
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data24_ = g_slice_new0 (Block24Data);
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data24_->_ref_count_ = 1;
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data24_->self = g_object_ref (self);
#line 110 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp0_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
#line 110 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp0_);
#line 110 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	separator = _tmp0_;
#line 111 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp1_ = self->postList;
#line 111 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp2_ = separator;
#line 111 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp3_ = self->postList;
#line 111 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp4_ = gtk_container_get_children ((GtkContainer*) _tmp3_);
#line 111 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp5_ = _tmp4_;
#line 111 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp6_ = g_list_length (_tmp5_);
#line 111 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_list_box_insert (_tmp1_, (GtkWidget*) _tmp2_, ((gint) _tmp6_) - 1);
#line 111 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_list_free0 (_tmp5_);
#line 112 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp7_ = post;
#line 112 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp8_ = photo_stream_widgets_post_box_new (_tmp7_);
#line 112 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp8_);
#line 112 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data24_->box = _tmp8_;
#line 114 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp9_ = (GtkListBoxRow*) gtk_list_box_row_new ();
#line 114 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_object_ref_sink (_tmp9_);
#line 114 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	listBoxRow = _tmp9_;
#line 116 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp10_ = listBoxRow;
#line 116 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp11_ = _data24_->box;
#line 116 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_container_add ((GtkContainer*) _tmp10_, (GtkWidget*) _tmp11_);
#line 117 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp12_ = self->postList;
#line 117 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp13_ = listBoxRow;
#line 117 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp14_ = self->postList;
#line 117 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp15_ = gtk_container_get_children ((GtkContainer*) _tmp14_);
#line 117 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp16_ = _tmp15_;
#line 117 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp17_ = g_list_length (_tmp16_);
#line 117 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_list_box_insert (_tmp12_, (GtkWidget*) _tmp13_, ((gint) _tmp17_) - 1);
#line 117 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_list_free0 (_tmp16_);
#line 118 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp18_ = _data24_->box;
#line 118 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp19_ = _g_object_ref0 (_tmp18_);
#line 118 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->boxes = g_list_append (self->boxes, _tmp19_);
#line 120 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp20_ = self->priv->cannotViewImages;
#line 120 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (!_tmp20_) {
#line 1355 "PostList.c"
		PhotoStreamWidgetsPostBox* _tmp21_ = NULL;
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp21_ = _data24_->box;
#line 122 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		g_signal_connect_data (_tmp21_, "image-loaded", (GCallback) ____lambda39__photo_stream_widgets_post_box_image_loaded, block24_data_ref (_data24_), (GClosureNotify) block24_data_unref, 0);
#line 1361 "PostList.c"
	}
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (listBoxRow);
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (separator);
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	block24_data_unref (_data24_);
#line 108 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_data24_ = NULL;
#line 1371 "PostList.c"
}


void photo_stream_widgets_post_list_resizeAllImages (PhotoStreamWidgetsPostList* self, gint windowSize) {
	gint _tmp0_ = 0;
	GList* _tmp1_ = NULL;
#line 184 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_if_fail (self != NULL);
#line 187 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp0_ = windowSize;
#line 187 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->IMAGE_SIZE = ((_tmp0_ - 10) / 3) - 1;
#line 188 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp1_ = self->boxes;
#line 1386 "PostList.c"
	{
		GList* box_collection = NULL;
		GList* box_it = NULL;
#line 188 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		box_collection = _tmp1_;
#line 188 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		for (box_it = box_collection; box_it != NULL; box_it = box_it->next) {
#line 1394 "PostList.c"
			PhotoStreamWidgetsPostBox* _tmp2_ = NULL;
			PhotoStreamWidgetsPostBox* box = NULL;
#line 188 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp2_ = _g_object_ref0 ((PhotoStreamWidgetsPostBox*) box_it->data);
#line 188 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			box = _tmp2_;
#line 1401 "PostList.c"
			{
				gint index = 0;
				GList* _tmp3_ = NULL;
				PhotoStreamWidgetsPostBox* _tmp4_ = NULL;
				gint _tmp5_ = 0;
				GtkGrid* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				gint _tmp8_ = 0;
				GtkWidget* _tmp9_ = NULL;
				gint _tmp10_ = 0;
				PhotoStreamWidgetsPostBox* _tmp11_ = NULL;
				PhotoStreamUtilsMediaInfo* _tmp12_ = NULL;
				gint _tmp13_ = 0;
#line 190 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp3_ = self->boxes;
#line 190 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp4_ = box;
#line 190 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp5_ = g_list_index (_tmp3_, _tmp4_);
#line 190 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				index = _tmp5_;
#line 191 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp6_ = self->imagesGrid;
#line 191 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp7_ = index;
#line 191 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp8_ = index;
#line 191 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp9_ = gtk_grid_get_child_at (_tmp6_, _tmp7_ % 3, _tmp8_ / 3);
#line 191 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				if (_tmp9_ == NULL) {
#line 192 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
					_g_object_unref0 (box);
#line 192 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
					continue;
#line 1437 "PostList.c"
				}
#line 194 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp10_ = index;
#line 194 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp11_ = box;
#line 194 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp12_ = _tmp11_->post;
#line 194 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp13_ = _tmp12_->type;
#line 194 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				photo_stream_widgets_post_list_loadImageToFeed (self, _tmp10_, _tmp13_ == PHOTO_STREAM_MEDIA_TYPE_VIDEO);
#line 195 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				gtk_widget_show_all ((GtkWidget*) self);
#line 188 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_g_object_unref0 (box);
#line 1453 "PostList.c"
			}
		}
	}
}


static void photo_stream_widgets_post_list_loadImageToFeed (PhotoStreamWidgetsPostList* self, gint index, gboolean isVideo) {
	GdkPixbuf* imagePixbuf = NULL;
	GdkPixbuf* videoPixbuf = NULL;
	GtkBin* container = NULL;
	GtkGrid* _tmp19_ = NULL;
	gint _tmp20_ = 0;
	gint _tmp21_ = 0;
	GtkWidget* _tmp22_ = NULL;
	GtkBin* _tmp23_ = NULL;
	GtkImage* image = NULL;
	GtkWidget* _tmp24_ = NULL;
	GtkImage* _tmp25_ = NULL;
	GdkPixbuf* _tmp26_ = NULL;
	GError * _inner_error_ = NULL;
#line 199 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_if_fail (self != NULL);
#line 1476 "PostList.c"
	{
		GList* _tmp0_ = NULL;
		gint _tmp1_ = 0;
		GList* _tmp2_ = NULL;
		gconstpointer _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		GdkPixbuf* _tmp6_ = NULL;
		gboolean _tmp7_ = FALSE;
#line 205 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp0_ = self->srcImages;
#line 205 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp1_ = index;
#line 205 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp2_ = g_list_nth (_tmp0_, (guint) _tmp1_);
#line 205 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp3_ = _tmp2_->data;
#line 205 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp4_ = self->IMAGE_SIZE;
#line 205 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp5_ = self->IMAGE_SIZE;
#line 205 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp6_ = gdk_pixbuf_scale_simple ((GdkPixbuf*) _tmp3_, _tmp4_, _tmp5_, GDK_INTERP_BILINEAR);
#line 205 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_object_unref0 (imagePixbuf);
#line 205 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		imagePixbuf = _tmp6_;
#line 206 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp7_ = isVideo;
#line 206 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		if (_tmp7_) {
#line 1508 "PostList.c"
			GdkPixbuf* _tmp8_ = NULL;
			GdkPixbuf* _tmp9_ = NULL;
			GdkPixbuf* _tmp10_ = NULL;
			GdkPixbuf* _tmp11_ = NULL;
			gint _tmp12_ = 0;
			gint _tmp13_ = 0;
			GdkPixbuf* _tmp14_ = NULL;
			GdkPixbuf* _tmp15_ = NULL;
			GdkPixbuf* _tmp16_ = NULL;
			gint _tmp17_ = 0;
			gint _tmp18_ = 0;
#line 208 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp9_ = gdk_pixbuf_new_from_file (PHOTO_STREAM_APP_CACHE_IMAGES "video.png", &_inner_error_);
#line 208 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp8_ = _tmp9_;
#line 208 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1526 "PostList.c"
				goto __catch31_g_error;
			}
#line 208 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp10_ = _tmp8_;
#line 208 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp8_ = NULL;
#line 208 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_g_object_unref0 (videoPixbuf);
#line 208 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			videoPixbuf = _tmp10_;
#line 209 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp11_ = videoPixbuf;
#line 209 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp12_ = self->IMAGE_SIZE;
#line 209 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp13_ = self->IMAGE_SIZE;
#line 209 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp14_ = gdk_pixbuf_scale_simple (_tmp11_, _tmp12_, _tmp13_, GDK_INTERP_BILINEAR);
#line 209 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_g_object_unref0 (videoPixbuf);
#line 209 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			videoPixbuf = _tmp14_;
#line 210 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp15_ = videoPixbuf;
#line 210 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp16_ = imagePixbuf;
#line 210 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp17_ = self->IMAGE_SIZE;
#line 210 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_tmp18_ = self->IMAGE_SIZE;
#line 210 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			gdk_pixbuf_composite (_tmp15_, _tmp16_, 0, 0, _tmp17_, _tmp18_, (gdouble) 0, (gdouble) 0, 1.0, 1.0, GDK_INTERP_BILINEAR, 255);
#line 206 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			_g_object_unref0 (_tmp8_);
#line 1561 "PostList.c"
		}
	}
	goto __finally31;
	__catch31_g_error:
	{
		GError* e = NULL;
#line 203 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		e = _inner_error_;
#line 203 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_inner_error_ = NULL;
#line 216 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		g_error ("PostList.vala:216: Something wrong with file loading.\n");
#line 203 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_error_free0 (e);
#line 1576 "PostList.c"
	}
	__finally31:
#line 203 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 203 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_object_unref0 (videoPixbuf);
#line 203 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_object_unref0 (imagePixbuf);
#line 203 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 203 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		g_clear_error (&_inner_error_);
#line 203 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		return;
#line 1591 "PostList.c"
	}
#line 220 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp19_ = self->imagesGrid;
#line 220 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp20_ = index;
#line 220 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp21_ = index;
#line 220 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp22_ = gtk_grid_get_child_at (_tmp19_, _tmp20_ % 3, _tmp21_ / 3);
#line 220 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp23_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp22_, gtk_bin_get_type (), GtkBin));
#line 220 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	container = _tmp23_;
#line 221 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp24_ = gtk_bin_get_child (container);
#line 221 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp25_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp24_, gtk_image_get_type (), GtkImage));
#line 221 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	image = _tmp25_;
#line 222 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp26_ = imagePixbuf;
#line 222 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	gtk_image_set_from_pixbuf (image, _tmp26_);
#line 199 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (image);
#line 199 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (container);
#line 199 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (videoPixbuf);
#line 199 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (imagePixbuf);
#line 1623 "PostList.c"
}


void photo_stream_widgets_post_list_clear (PhotoStreamWidgetsPostList* self) {
	GtkListBox* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
	gboolean _tmp6_ = FALSE;
	GtkAlignment* _tmp7_ = NULL;
	GtkListBox* _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
#line 225 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_return_if_fail (self != NULL);
#line 227 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp0_ = self->postList;
#line 227 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp1_ = gtk_container_get_children ((GtkContainer*) _tmp0_);
#line 1640 "PostList.c"
	{
		GList* child_collection = NULL;
		GList* child_it = NULL;
#line 227 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		child_collection = _tmp1_;
#line 227 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
#line 1648 "PostList.c"
			GtkWidget* child = NULL;
#line 227 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
			child = (GtkWidget*) child_it->data;
#line 1652 "PostList.c"
			{
				GtkWidget* _tmp2_ = NULL;
				GtkWidget* _tmp3_ = NULL;
#line 228 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp2_ = child;
#line 228 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				_tmp3_ = gtk_bin_get_child ((GtkBin*) G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, gtk_list_box_row_get_type (), GtkListBoxRow));
#line 228 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
				if (!G_TYPE_CHECK_INSTANCE_TYPE (_tmp3_, gtk_alignment_get_type ())) {
#line 1662 "PostList.c"
					GtkListBox* _tmp4_ = NULL;
					GtkWidget* _tmp5_ = NULL;
#line 229 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
					_tmp4_ = self->postList;
#line 229 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
					_tmp5_ = child;
#line 229 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
					gtk_container_remove ((GtkContainer*) _tmp4_, _tmp5_);
#line 1671 "PostList.c"
				}
			}
		}
#line 227 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_g_list_free0 (child_collection);
#line 1677 "PostList.c"
	}
#line 231 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	__g_list_free__g_object_unref0_0 (self->boxes);
#line 231 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->boxes = NULL;
#line 233 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp7_ = self->moreButtonAlignment;
#line 233 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp8_ = self->postList;
#line 233 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_tmp9_ = gtk_widget_is_ancestor ((GtkWidget*) _tmp7_, (GtkWidget*) _tmp8_);
#line 233 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (!_tmp9_) {
#line 1691 "PostList.c"
		const gchar* _tmp10_ = NULL;
#line 233 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp10_ = self->olderFeedLink;
#line 233 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp6_ = g_strcmp0 (_tmp10_, "") != 0;
#line 1697 "PostList.c"
	} else {
#line 233 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp6_ = FALSE;
#line 1701 "PostList.c"
	}
#line 233 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	if (_tmp6_) {
#line 1705 "PostList.c"
		GtkListBox* _tmp11_ = NULL;
		GtkAlignment* _tmp12_ = NULL;
#line 234 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp11_ = self->postList;
#line 234 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		_tmp12_ = self->moreButtonAlignment;
#line 234 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
		gtk_list_box_prepend (_tmp11_, (GtkWidget*) _tmp12_);
#line 1714 "PostList.c"
	}
}


static void photo_stream_widgets_post_list_class_init (PhotoStreamWidgetsPostListClass * klass) {
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	photo_stream_widgets_post_list_parent_class = g_type_class_peek_parent (klass);
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	g_type_class_add_private (klass, sizeof (PhotoStreamWidgetsPostListPrivate));
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	G_OBJECT_CLASS (klass)->finalize = photo_stream_widgets_post_list_finalize;
#line 1726 "PostList.c"
}


static void photo_stream_widgets_post_list_instance_init (PhotoStreamWidgetsPostList * self) {
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self->priv = PHOTO_STREAM_WIDGETS_POST_LIST_GET_PRIVATE (self);
#line 1733 "PostList.c"
}


static void photo_stream_widgets_post_list_finalize (GObject* obj) {
	PhotoStreamWidgetsPostList * self;
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PHOTO_STREAM_WIDGETS_TYPE_POST_LIST, PhotoStreamWidgetsPostList);
#line 7 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	__g_list_free__g_object_unref0_0 (self->boxes);
#line 8 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	__g_list_free__g_object_unref0_0 (self->srcImages);
#line 9 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->moreButton);
#line 10 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->moreButtonAlignment);
#line 11 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->moreButtonImages);
#line 12 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->moreButtonImagesAlignment);
#line 13 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_free0 (self->olderFeedLink);
#line 16 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->postsWindow);
#line 17 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->imagesWindow);
#line 19 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->stack);
#line 20 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->postList);
#line 21 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->imagesBox);
#line 22 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->imagesGrid);
#line 24 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	_g_object_unref0 (self->priv->parentWindow);
#line 5 "/all/Documents/Programming/vala/photostream/src/Widgets/PostList.vala"
	G_OBJECT_CLASS (photo_stream_widgets_post_list_parent_class)->finalize (obj);
#line 1771 "PostList.c"
}


GType photo_stream_widgets_post_list_get_type (void) {
	static volatile gsize photo_stream_widgets_post_list_type_id__volatile = 0;
	if (g_once_init_enter (&photo_stream_widgets_post_list_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PhotoStreamWidgetsPostListClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) photo_stream_widgets_post_list_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PhotoStreamWidgetsPostList), 0, (GInstanceInitFunc) photo_stream_widgets_post_list_instance_init, NULL };
		GType photo_stream_widgets_post_list_type_id;
		photo_stream_widgets_post_list_type_id = g_type_register_static (gtk_box_get_type (), "PhotoStreamWidgetsPostList", &g_define_type_info, 0);
		g_once_init_leave (&photo_stream_widgets_post_list_type_id__volatile, photo_stream_widgets_post_list_type_id);
	}
	return photo_stream_widgets_post_list_type_id__volatile;
}



